project_id = "arcuhqdiydlvekanychw"

[functions.nps-public-get]
verify_jwt = false

[functions.nps-public-submit]
verify_jwt = false

[functions.nps-public-status]
verify_jwt = false

[functions.nps-webhooks-dispatch]
verify_jwt = false

[functions.nps-alerts-dispatch]
verify_jwt = false

[functions.nps-automation-dispatch]
verify_jwt = false

