import { lazy } from 'react';
import { Route } from 'react-router-dom';

const AccountsPayable = lazy(() => import("../modules/financial/AccountsPayable"));
const AccountsReceivable = lazy(() => import("../modules/financial/AccountsReceivable"));
const CashFlow = lazy(() => import("../modules/financial/CashFlow"));
const BankReconciliation = lazy(() => import("../modules/financial/BankReconciliation"));
const FinancialDashboardPage = lazy(() => import("../modules/financial/FinancialDashboard"));
const BankAccountsPage = lazy(() => import("../modules/financial/BankAccounts"));
const CostCentersPage = lazy(() => import("../modules/financial/CostCenters"));
const RenegotiationsPage = lazy(() => import("../modules/financial/Renegotiations"));
const DRELedgerPage = lazy(() => import("../modules/financial/DRELedger"));
const FinancialAuditPage = lazy(() => import("../modules/financial/FinancialAudit"));
const PixChargesPage = lazy(() => import("../modules/financial/PixCharges"));
const ChecksPage = lazy(() => import("../modules/financial/Checks"));
const BoletosPage = lazy(() => import("../modules/financial/Boletos"));
const FinancialIntelligencePage = lazy(() => import("../modules/financial/FinancialIntelligence"));
const FinancialBIPage = lazy(() => import("../modules/financial/FinancialBI"));
const FinancialAntifraudPage = lazy(() => import("../modules/financial/FinancialAntifraud"));
const BankStatementImportPage = lazy(() => import("../modules/financial/BankStatementImport"));
const AdvancesPage = lazy(() => import("../modules/financial/Advances"));
const FinancialHubPage = lazy(() => import("../modules/financial/FinancialHub"));
const AccountStatementPage = lazy(() => import("../modules/financial/AccountStatement"));
const FinancialOffsetPage = lazy(() => import("../modules/financial/FinancialOffset"));
const ChargesRulerPage = lazy(() => import("../modules/financial/ChargesRuler"));
const RecurringPage = lazy(() => import("../modules/financial/RecurringPage"));
const DefaultManagementPage = lazy(() => import("../modules/financial/DefaultManagement"));
const CashflowScenariosPage = lazy(() => import("../modules/financial/CashflowScenarios"));
const FinancialAlertsPage = lazy(() => import("../modules/financial/FinancialAlerts"));
const DREDynamicPage = lazy(() => import("../modules/financial/DREDynamicPage"));

export const FinancialRoutes = [
  <Route key="fin-hub" path="/financial/central" element={<FinancialHubPage />} />,
  <Route key="fin-dash" path="/financial/dashboard" element={<FinancialDashboardPage />} />,
  <Route key="fin-pay" path="/financial/pagar" element={<AccountsPayable />} />,
  <Route key="fin-rec" path="/financial/receber" element={<AccountsReceivable />} />,
  <Route key="fin-flow" path="/financial/fluxo" element={<CashFlow />} />,
  <Route key="fin-bank" path="/financial/tesouraria" element={<BankAccountsPage />} />,
  <Route key="fin-cc" path="/financial/centros-custo" element={<CostCentersPage />} />,
  <Route key="fin-reneg" path="/financial/renegociacoes" element={<RenegotiationsPage />} />,
  <Route key="fin-recon" path="/financial/conciliacao" element={<BankReconciliation />} />,
  <Route key="fin-dre" path="/financial/dre" element={<DRELedgerPage />} />,
  <Route key="fin-audit" path="/financial/auditoria" element={<FinancialAuditPage />} />,
  <Route key="fin-pix" path="/financial/pix" element={<PixChargesPage />} />,
  <Route key="fin-checks" path="/financial/cheques" element={<ChecksPage />} />,
  <Route key="fin-boletos" path="/financial/boletos" element={<BoletosPage />} />,
  <Route key="fin-intel" path="/financial/inteligencia" element={<FinancialIntelligencePage />} />,
  <Route key="fin-bi" path="/financial/bi" element={<FinancialBIPage />} />,
  <Route key="fin-fraud" path="/financial/antifraude" element={<FinancialAntifraudPage />} />,
  <Route key="fin-import" path="/financial/importar-extrato" element={<BankStatementImportPage />} />,
  <Route key="fin-adv" path="/financial/adiantamentos" element={<AdvancesPage />} />,
  <Route key="fin-stmt" path="/financial/conta-corrente" element={<AccountStatementPage />} />,
  <Route key="fin-offset" path="/financial/compensacao" element={<FinancialOffsetPage />} />,
  <Route key="fin-ruler" path="/financial/cobranca-automatica" element={<ChargesRulerPage />} />,
  <Route key="fin-recur" path="/financial/recorrencias" element={<RecurringPage />} />,
  <Route key="fin-default" path="/financial/inadimplencia" element={<DefaultManagementPage />} />,
  <Route key="fin-scen" path="/financial/cenarios" element={<CashflowScenariosPage />} />,
  <Route key="fin-alerts" path="/financial/alertas" element={<FinancialAlertsPage />} />,
  <Route key="fin-dre-dyn" path="/financial/dre-dinamico" element={<DREDynamicPage />} />,
];
