import { lazy } from 'react';
import { Route } from 'react-router-dom';

const ProductionOrdersPage = lazy(() => import("../modules/production/ProductionOrders"));
const MaterialConsumptionPage = lazy(() => import("../modules/production/MaterialConsumption"));
const TimeEntriesPage = lazy(() => import("../modules/production/TimeEntries"));
const PCPPanelPage = lazy(() => import("../modules/production/PCPPanel"));
const ProductionStepsPage = lazy(() => import("../modules/production/ProductionSteps"));
const ProductionQueuePage = lazy(() => import("../modules/production/ProductionQueue"));
const QualityControlPage = lazy(() => import("../modules/production/QualityControl"));
const SupplyStockPage = lazy(() => import("../modules/production/SupplyStock"));
const ProductCostsPage = lazy(() => import("../modules/production/ProductCosts"));
const IndustrialDashboardPage = lazy(() => import("../modules/production/IndustrialDashboard"));
const OperatorTerminalPage = lazy(() => import("../modules/production/OperatorTerminal"));
const ShopFloorDashboardPage = lazy(() => import("../modules/production/ShopFloorDashboard"));
const ProductionKanbanPage = lazy(() => import("../modules/production/ProductionKanban"));
const TechnicalSheetsPage = lazy(() => import("../modules/production/TechnicalSheets"));
const ProductionCapacityPage = lazy(() => import("../modules/production/ProductionCapacity"));
const ProductionTraceabilityPage = lazy(() => import("../modules/production/ProductionTraceability"));
const AIProductionPage = lazy(() => import("../modules/production/AIProductionPage"));
const ProductionSchedulePage = lazy(() => import("../modules/production/ProductionSchedule"));
const MRPPage = lazy(() => import("../modules/production/MRPPage"));
const BIIndustrialPage = lazy(() => import("../modules/production/BIIndustrial"));
const DigitalTwinPage = lazy(() => import("../modules/production/DigitalTwin"));
const APSPageComponent = lazy(() => import("../modules/production/APSPage"));
const IoTDashboardPage = lazy(() => import("../modules/production/IoTDashboard"));
const OEEDashboardPage = lazy(() => import("../modules/production/OEEDashboard"));
const MLPredictionsPage = lazy(() => import("../modules/production/MLPredictions"));
const ProductionSectorsPage = lazy(() => import("../modules/production/ProductionSectors"));
const ProductionLinesPage = lazy(() => import("../modules/production/ProductionLinesPage"));
const ProductionResourcesPage = lazy(() => import("../modules/production/ProductionResourcesPage"));
const ProductionRoutesPage = lazy(() => import("../modules/production/ProductionRoutesPage"));
const OutsourcingPage = lazy(() => import("../modules/production/OutsourcingPage"));

export const ProductionRoutes = [
  <Route key="prod-orders" path="/producao/ordens" element={<ProductionOrdersPage />} />,
  <Route key="prod-cons" path="/producao/consumo" element={<MaterialConsumptionPage />} />,
  <Route key="prod-time" path="/producao/apontamento" element={<TimeEntriesPage />} />,
  <Route key="prod-pcp" path="/producao/pcp" element={<PCPPanelPage />} />,
  <Route key="prod-steps" path="/producao/etapas" element={<ProductionStepsPage />} />,
  <Route key="prod-queue" path="/producao/fila" element={<ProductionQueuePage />} />,
  <Route key="prod-quality" path="/producao/qualidade" element={<QualityControlPage />} />,
  <Route key="prod-supply" path="/producao/insumos" element={<SupplyStockPage />} />,
  <Route key="prod-costs" path="/producao/custos" element={<ProductCostsPage />} />,
  <Route key="prod-dash" path="/producao/dashboard" element={<IndustrialDashboardPage />} />,
  <Route key="prod-term" path="/producao/terminal" element={<OperatorTerminalPage />} />,
  <Route key="prod-shop" path="/producao/chao-de-fabrica" element={<ShopFloorDashboardPage />} />,
  <Route key="prod-kanban" path="/producao/kanban" element={<ProductionKanbanPage />} />,
  <Route key="prod-tech" path="/producao/fichas" element={<TechnicalSheetsPage />} />,
  <Route key="prod-cap" path="/producao/capacidade" element={<ProductionCapacityPage />} />,
  <Route key="prod-trace" path="/producao/rastreabilidade" element={<ProductionTraceabilityPage />} />,
  <Route key="prod-ia" path="/producao/ia" element={<AIProductionPage />} />,
  <Route key="prod-sched" path="/producao/programacao" element={<ProductionSchedulePage />} />,
  <Route key="prod-mrp" path="/producao/mrp" element={<MRPPage />} />,
  <Route key="prod-bi" path="/producao/bi" element={<BIIndustrialPage />} />,
  <Route key="prod-twin" path="/producao/twin" element={<DigitalTwinPage />} />,
  <Route key="prod-aps" path="/producao/aps" element={<APSPageComponent />} />,
  <Route key="prod-iot" path="/producao/iot" element={<IoTDashboardPage />} />,
  <Route key="prod-oee" path="/producao/oee" element={<OEEDashboardPage />} />,
  <Route key="prod-ml" path="/producao/previsoes" element={<MLPredictionsPage />} />,
  <Route key="prod-sect" path="/producao/setores" element={<ProductionSectorsPage />} />,
  <Route key="prod-lines" path="/producao/linhas" element={<ProductionLinesPage />} />,
  <Route key="prod-res" path="/producao/recursos" element={<ProductionResourcesPage />} />,
  <Route key="prod-routes" path="/producao/roteiros" element={<ProductionRoutesPage />} />,
  <Route key="prod-out" path="/producao/terceirizacao" element={<OutsourcingPage />} />,
];
