import { lazy } from 'react';
import { Route } from 'react-router-dom';

const WMSDashboardPage = lazy(() => import("../modules/wms/WMSDashboard"));
const ReceivingPage = lazy(() => import("../modules/wms/Receiving"));
const StoragePage = lazy(() => import("../modules/wms/Storage"));
const PickingPage = lazy(() => import("../modules/wms/Picking"));
const PackingPage = lazy(() => import("../modules/wms/Packing"));
const InventoryPage = lazy(() => import("../modules/wms/Inventory"));
const WMSMovementsPage = lazy(() => import("../modules/wms/Movements"));
const ConferencePage = lazy(() => import("../modules/wms/Conference"));
const ShipmentsPage = lazy(() => import("../modules/wms/Shipments"));
const LotsPage = lazy(() => import("../modules/wms/Lots"));
const WavesPage = lazy(() => import("../modules/wms/Waves"));
const PutawayPage = lazy(() => import("../modules/wms/Putaway"));
const ReplenishmentPage = lazy(() => import("../modules/wms/Replenishment"));
const ReturnsPage = lazy(() => import("../modules/wms/Returns"));
const DistributionCentersPage = lazy(() => import("../modules/wms/DistributionCenters"));
const StockBalancesPage = lazy(() => import("../modules/wms/StockBalances"));
const DocksPage = lazy(() => import("../modules/wms/Docks"));
const WMSAIPage = lazy(() => import("../modules/wms/WMSAI"));
const DigitalTwinPage = lazy(() => import("../modules/wms/twin/DigitalTwin"));
const IntelligencePage = lazy(() => import("../modules/wms/intelligence/Intelligence"));
const SlottingPlannerPage = lazy(() => import("../modules/wms/slotting/SlottingPlanner"));
const YardManagementPage = lazy(() => import("../modules/wms/yard/YardManagement"));

export const WMSRoutes = [
  <Route key="wms-dash" path="/wms/dashboard" element={<WMSDashboardPage />} />,
  <Route key="wms-rec" path="/wms/recebimento" element={<ReceivingPage />} />,
  <Route key="wms-store" path="/wms/armazenagem" element={<StoragePage />} />,
  <Route key="wms-pick" path="/wms/separacao" element={<PickingPage />} />,
  <Route key="wms-pack" path="/wms/embalagem" element={<PackingPage />} />,
  <Route key="wms-inv" path="/wms/inventario" element={<InventoryPage />} />,
  <Route key="wms-mov" path="/wms/movimentacoes" element={<WMSMovementsPage />} />,
  <Route key="wms-conf" path="/wms/conferencia" element={<ConferencePage />} />,
  <Route key="wms-ship" path="/wms/expedicao" element={<ShipmentsPage />} />,
  <Route key="wms-lots" path="/wms/lotes" element={<LotsPage />} />,
  <Route key="wms-waves" path="/wms/ondas" element={<WavesPage />} />,
  <Route key="wms-put" path="/wms/putaway" element={<PutawayPage />} />,
  <Route key="wms-rep" path="/wms/ressuprimento" element={<ReplenishmentPage />} />,
  <Route key="wms-ret" path="/wms/devolucoes" element={<ReturnsPage />} />,
  <Route key="wms-dc" path="/wms/centros-distribuicao" element={<DistributionCentersPage />} />,
  <Route key="wms-bal" path="/wms/saldos" element={<StockBalancesPage />} />,
  <Route key="wms-docks" path="/wms/docas" element={<DocksPage />} />,
  <Route key="wms-ai" path="/wms/ia" element={<WMSAIPage />} />,
  <Route key="wms-twin" path="/wms/twin" element={<DigitalTwinPage />} />,
  <Route key="wms-intel" path="/wms/inteligencia" element={<IntelligencePage />} />,
  <Route key="wms-slot" path="/wms/slotting" element={<SlottingPlannerPage />} />,
  <Route key="wms-yard" path="/wms/yard" element={<YardManagementPage />} />,
];
