import { lazy } from 'react';
import { Route, Navigate } from 'react-router-dom';

const WMSDashboardPage = lazy(() => import("../modules/wms/WMSDashboard"));
const ReceivingPage = lazy(() => import("../modules/wms/Receiving"));
const StoragePage = lazy(() => import("../modules/wms/Storage"));
const PickingPage = lazy(() => import("../modules/wms/Picking"));
const PackingPage = lazy(() => import("../modules/wms/Packing"));
const InventoryPage = lazy(() => import("../modules/wms/Inventory"));
const WMSMovementsPage = lazy(() => import("../modules/wms/Movements"));
const ConferencePage = lazy(() => import("../modules/wms/Conference"));
const ShipmentsPage = lazy(() => import("../modules/wms/Shipments"));
const LotsPage = lazy(() => import("../modules/wms/Lots"));
const WavesPage = lazy(() => import("../modules/wms/Waves"));
const PutawayPage = lazy(() => import("../modules/wms/Putaway"));
const ReplenishmentPage = lazy(() => import("../modules/wms/Replenishment"));
const ReturnsPage = lazy(() => import("../modules/wms/Returns"));
const DistributionCentersPage = lazy(() => import("../modules/wms/DistributionCenters"));
const StockBalancesPage = lazy(() => import("../modules/wms/StockBalances"));
const DocksPage = lazy(() => import("../modules/wms/Docks"));
const WMSAIPage = lazy(() => import("../modules/wms/WMSAI"));
const DigitalTwinPage = lazy(() => import("../modules/wms/twin/DigitalTwin"));
const IntelligencePage = lazy(() => import("../modules/wms/intelligence/Intelligence"));
const SlottingPlannerPage = lazy(() => import("../modules/wms/slotting/SlottingPlanner"));
const YardManagementPage = lazy(() => import("../modules/wms/yard/YardManagement"));
const LocationsPage = lazy(() => import("../modules/wms/Locations"));
const SkuAllocationPage = lazy(() => import("../modules/wms/SkuAllocation"));
const OrderReservationsPage = lazy(() => import("../modules/wms/OrderReservations"));
const OrderPickingPage = lazy(() => import("../modules/wms/OrderPicking"));
const QualityControlPage = lazy(() => import("../modules/wms/QualityControl"));
const Billing3PLPage = lazy(() => import("../modules/wms/Billing3PL"));
const PickingRoutePage = lazy(() => import("../modules/wms/PickingRouteOptimizer"));
const LaborManagementPage = lazy(() => import("../modules/wms/LaborManagement"));
const CycleCountPage = lazy(() => import("../modules/wms/CycleCount"));
const WMSAnalyticsPage = lazy(() => import("../modules/wms/WMSAnalytics"));
const CrossDockingPage = lazy(() => import("../modules/wms/CrossDocking"));
const KitAssemblyPage = lazy(() => import("../modules/wms/KitAssembly"));
const DockSchedulingPage = lazy(() => import("../modules/wms/DockScheduling"));
const CarrierScorecardPage = lazy(() => import("../modules/wms/CarrierScorecard"));
const WavePlanningV2Page = lazy(() => import("../modules/wms/WavePlanningV2"));
const EstoqueMatrixPage = lazy(() => import("../modules/wms/EstoqueMatrix"));

export const WMSRoutes = [
  <Route key="wms-index" index element={<Navigate to="dashboard" replace />} />,
  <Route key="wms-dash" path="dashboard" element={<WMSDashboardPage />} />,
  <Route key="wms-rec" path="recebimento" element={<ReceivingPage />} />,
  <Route key="wms-store" path="armazenagem" element={<StoragePage />} />,
  <Route key="wms-pick" path="separacao" element={<PickingPage />} />,
  <Route key="wms-pack" path="embalagem" element={<PackingPage />} />,
  <Route key="wms-inv" path="inventario" element={<InventoryPage />} />,
  <Route key="wms-mov" path="movimentacoes" element={<WMSMovementsPage />} />,
  <Route key="wms-conf" path="conferencia" element={<ConferencePage />} />,
  <Route key="wms-ship" path="expedicao" element={<ShipmentsPage />} />,
  <Route key="wms-lots" path="lotes" element={<LotsPage />} />,
  <Route key="wms-waves" path="ondas" element={<WavesPage />} />,
  <Route key="wms-put" path="putaway" element={<PutawayPage />} />,
  <Route key="wms-rep" path="ressuprimento" element={<ReplenishmentPage />} />,
  <Route key="wms-ret" path="devolucoes" element={<ReturnsPage />} />,
  <Route key="wms-dc" path="centros-distribuicao" element={<DistributionCentersPage />} />,
  <Route key="wms-bal" path="saldos" element={<StockBalancesPage />} />,
  <Route key="wms-docks" path="docas" element={<DocksPage />} />,
  <Route key="wms-ai" path="ia" element={<WMSAIPage />} />,
  <Route key="wms-twin" path="twin" element={<DigitalTwinPage />} />,
  <Route key="wms-intel" path="inteligencia" element={<IntelligencePage />} />,
  <Route key="wms-slot" path="slotting" element={<SlottingPlannerPage />} />,
  <Route key="wms-yard" path="yard" element={<YardManagementPage />} />,
  <Route key="wms-locs" path="enderecos" element={<LocationsPage />} />,
  <Route key="wms-alloc" path="alocacao" element={<SkuAllocationPage />} />,
  <Route key="wms-reserv" path="reservas" element={<OrderReservationsPage />} />,
  <Route key="wms-picking" path="separacao-pedidos" element={<OrderPickingPage />} />,
  <Route key="wms-quality" path="qualidade" element={<QualityControlPage />} />,
  <Route key="wms-3pl" path="faturamento-3pl" element={<Billing3PLPage />} />,
  <Route key="wms-route" path="rota-picking" element={<PickingRoutePage />} />,
  <Route key="wms-labor" path="mao-de-obra" element={<LaborManagementPage />} />,
  <Route key="wms-cycle" path="inventario-ciclico" element={<CycleCountPage />} />,
  <Route key="wms-analytics" path="analytics" element={<WMSAnalyticsPage />} />,
  <Route key="wms-crossdock" path="cross-docking" element={<CrossDockingPage />} />,
  <Route key="wms-kits" path="kits" element={<KitAssemblyPage />} />,
  <Route key="wms-dock-sched" path="agenda-docas" element={<DockSchedulingPage />} />,
  <Route key="wms-carrier-score" path="scorecard-transportadoras" element={<CarrierScorecardPage />} />,
  <Route key="wms-wave-v2" path="wave-planning" element={<WavePlanningV2Page />} />,
  <Route key="wms-matrix" path="matriz-estoque" element={<EstoqueMatrixPage />} />,
];
