import {
  LayoutDashboard, Users, Wallet, FileCheck, Package, ShoppingCart,
  Factory, Warehouse, Settings, UserCircle, Monitor,
  ShoppingBag, ClipboardList, FileText, ArrowUpCircle, ArrowDownCircle,
  TrendingUp, CheckCircle, Receipt, BarChart3, Box, FolderTree,
  ArrowLeftRight, Calculator, Building2, FileSearch, ClipboardCheck,
  PackageMinus, Timer, PackagePlus, MapPin, PackageSearch, PackageCheck,
  MoveHorizontal, Building, Sliders, Plug, BookOpen, Scale,
  Radio, Wifi, Tag, Activity, Brain, Gauge, Columns, ListOrdered,
  CalendarClock, Smartphone, Rows3, Wrench, Route, Layers, Zap,
  ShieldCheck, Search, Boxes, PieChart, CircleGauge, Sparkles, Cpu, Rocket,
  Filter, UserCheck, DollarSign, Target, Megaphone, Trophy, Bot,
  Eye, Truck, RefreshCw, Shield, Lock, Phone,
  ArrowDown, Database, ScanBarcode, DoorOpen, RotateCcw,
  Bell, Repeat, TrendingDown, LineChart, AlertTriangle,
  ShieldAlert, Upload, QrCode, FileCheck2, FileDown,
  Percent, Globe, ScrollText, ArrowRightLeft,
  BellRing, RotateCw, AlertOctagon, GitBranch, Siren, Scissors, Inbox, Heart,
  Send, MessageSquare, Palette, BookOpenCheck, Crown, LayoutGrid, Split, FileBarChart, Navigation,
  Activity, ArrowLeftRight, ArrowDownCircle, ArrowUpCircle, BarChart3, BookOpen, Box, Brain, Building,
  Building2, Calculator, CalendarClock, CheckCircle, CircleGauge, ClipboardCheck, ClipboardList,
  Columns, Cpu, Database, DollarSign, DoorOpen, Eye, Factory, FileCheck, FileCheck2, FileDown,
  FileSearch, FileText, Filter, FolderTree, Gauge, Globe, History, Layers, LayoutDashboard, LineChart,
  ListOrdered, Lock, MapPin, Megaphone, Monitor, MoveHorizontal, Package, PackageCheck, PackageMinus,
  PackagePlus, PackageSearch, Percent, Phone, PieChart, Plug, QrCode, Radio, Receipt, RefreshCw,
  Repeat, Rocket, RotateCcw, Route, Rows3, ScanBarcode, Scale, ScrollText, Search, Settings, Shield,
  ShieldAlert, ShieldCheck, ShoppingBag, ShoppingCart, Sliders, Smartphone, Sparkles, Target, Trophy,
  Truck, UserCheck, UserCircle, Users, Wallet, Wifi, Wrench, Zap,
} from 'lucide-react';

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  LayoutDashboard, Users, Wallet, FileCheck, Package, ShoppingCart,
  Factory, Warehouse, Settings, UserCircle, ShoppingBag, ClipboardList, Crown, Monitor,
  FileText, ArrowUpCircle, ArrowDownCircle, TrendingUp, CheckCircle,
  Receipt, BarChart3, Box, FolderTree, ArrowLeftRight, Calculator,
  Building2, FileSearch, ClipboardCheck, PackageMinus, Timer, PackagePlus,
  MapPin, PackageSearch, PackageCheck, MoveHorizontal, Building, Sliders,
  Plug, BookOpen, Scale, Radio, Wifi, Tag, Activity, Brain, Gauge,
  Columns, ListOrdered, CalendarClock, Smartphone, Rows3, Wrench, Route,
  Layers, Zap, ShieldCheck, Search, Boxes, PieChart, CircleGauge,
  Sparkles, Cpu, Rocket, Filter, UserCheck, DollarSign, Target,
  Megaphone, Trophy, Bot, Eye, Truck, RefreshCw,
  Shield, Lock, Phone, ArrowDown, Database, ScanBarcode, DoorOpen, RotateCcw,
  Bell, Repeat, TrendingDown, LineChart, AlertTriangle, ShieldAlert, Upload, QrCode,
  FileCheck2, FileDown, Percent, Globe, ScrollText, ArrowRightLeft,
  BellRing, RotateCw, AlertOctagon, GitBranch, Siren, Scissors, Inbox, Heart,
  Send, MessageSquare, Palette, BookOpenCheck, LayoutGrid, Split, FileBarChart, Navigation,
  History,
};
