import {
  LayoutDashboard, Users, Wallet, FileCheck, Package, ShoppingCart,
  Factory, Warehouse, Settings, UserCircle,
  ShoppingBag, ClipboardList, FileText, ArrowUpCircle, ArrowDownCircle,
  TrendingUp, CheckCircle, Receipt, BarChart3, Box, FolderTree,
  ArrowLeftRight, Calculator, Building2, FileSearch, ClipboardCheck,
  PackageMinus, Timer, PackagePlus, MapPin, PackageSearch, PackageCheck,
  MoveHorizontal, Building, Sliders, Plug, BookOpen, Scale,
  Radio, Wifi, Tag, Activity, Brain, Gauge, Columns, ListOrdered,
  CalendarClock, Smartphone, Rows3, Wrench, Route, Layers, Zap,
  ShieldCheck, Search, Boxes, PieChart, CircleGauge, Sparkles, Cpu, Rocket,
  Filter, UserCheck, DollarSign, Target, Megaphone, Trophy, Bot,
  Eye, Truck, RefreshCw, Shield, Lock, Phone,
  ArrowDown, Database, ScanBarcode, DoorOpen, RotateCcw,
  Bell, Repeat, TrendingDown, LineChart, AlertTriangle,
  ShieldAlert, Upload, QrCode, FileCheck2, FileDown,
  Percent, Globe, ScrollText, ArrowRightLeft,
  BellRing, RotateCw, AlertOctagon, GitBranch, Siren, Scissors,
  Inbox, Heart, Send, MessageSquare, Palette, BookOpenCheck, Crown, LayoutGrid, Split, FileBarChart,
} from 'lucide-react';

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  LayoutDashboard, Users, Wallet, FileCheck, Package, ShoppingCart,
  Factory, Warehouse, Settings, UserCircle, ShoppingBag, ClipboardList, Crown,
  FileText, ArrowUpCircle, ArrowDownCircle, TrendingUp, CheckCircle,
  Receipt, BarChart3, Box, FolderTree, ArrowLeftRight, Calculator,
  Building2, FileSearch, ClipboardCheck, PackageMinus, Timer, PackagePlus,
  MapPin, PackageSearch, PackageCheck, MoveHorizontal, Building, Sliders,
  Plug, BookOpen, Scale, Radio, Wifi, Tag, Activity, Brain, Gauge,
  Columns, ListOrdered, CalendarClock, Smartphone, Rows3, Wrench, Route,
  Layers, Zap, ShieldCheck, Search, Boxes, PieChart, CircleGauge,
  Sparkles, Cpu, Rocket, Filter, UserCheck, DollarSign, Target,
  Megaphone, Trophy, Bot, Eye, Truck, RefreshCw,
  Shield, Lock, Phone, ArrowDown, Database, ScanBarcode, DoorOpen, RotateCcw,
  Bell, Repeat, TrendingDown, LineChart, AlertTriangle, ShieldAlert, Upload, QrCode,
  FileCheck2, FileDown, Percent, Globe, ScrollText, ArrowRightLeft,
  BellRing, RotateCw, AlertOctagon, GitBranch, Siren, Scissors, Inbox, Heart,
  Send, MessageSquare, Palette, BookOpenCheck, LayoutGrid, Split, FileBarChart,
};
