import type { RoadmapPhase } from './foundation-types';

/**
 * Roteiro cronológico global de implantação de ERP.
 * Baseado em metodologia UEEF (Diagnóstico → Mapeamento → Desenho →
 * Implementação → Review Loop → Entrega) e boas práticas de mercado
 * (ASAP/Activate, Signature Method, Sure Step).
 */
export const IMPLEMENTATION_ROADMAP: RoadmapPhase[] = [
  {
    order: 1,
    code: 'F1',
    title: 'Fundação & Diagnóstico',
    goal: 'Entender o negócio, mapear processos AS-IS e desenhar o TO-BE.',
    duration: '3 a 5 dias',
    owner: 'Consultor + Sponsor',
    activities: [
      'Kickoff com diretoria: escopo, cronograma, riscos e critérios de sucesso.',
      'Levantamento AS-IS: como cada área trabalha hoje (planilhas, sistemas legados, dores).',
      'Mapa de integrações necessárias (bancos, e-commerce, marketplaces, contador).',
      'Definição de segmento e verticais (têxtil, farma, distribuição, agro, etc.).',
      'Escolha de matriz e filiais que vão entrar no piloto.',
    ],
    deliverable: 'Blueprint de implantação assinado pelo sponsor.',
    gate: 'Sponsor aprova escopo, prazos e responsáveis.',
    modules: ['admin-empresas', 'admin-usuarios', 'admin-parametros'],
  },
  {
    order: 2,
    code: 'F2',
    title: 'Cadastros mestres',
    goal: 'Popular a espinha dorsal do sistema. Sem cadastro correto, nada funciona.',
    duration: '5 a 10 dias',
    owner: 'Consultor + Chave de cada área',
    activities: [
      'Cadastro de empresas e filiais (CNPJ, regime tributário, IE, endereços).',
      'Importação de plano de contas contábeis (padrão ou personalizado).',
      'Cadastro de produtos: SKU, NCM, unidade, categoria, curva ABC inicial.',
      'Cadastro de clientes e fornecedores (via BrasilAPI onde possível).',
      'Configuração de CFOPs, CSTs, alíquotas e regras tributárias por UF.',
      'Bancos e contas correntes com saldos iniciais.',
      'Centros de custo e centros de trabalho (para produção).',
    ],
    deliverable: 'Bases mestres importadas e validadas amostralmente (>= 95% integridade).',
    gate: 'Amostra de 20 registros por cadastro conferida contra origem sem divergências.',
    modules: ['admin-empresas', 'estoque', 'compras', 'comercial', 'contabilidade', 'fiscal'],
  },
  {
    order: 3,
    code: 'F3',
    title: 'Segurança, papéis e alçadas',
    goal: 'Definir quem faz o quê. Nada de operar como admin universal.',
    duration: '2 a 3 dias',
    owner: 'Consultor + TI',
    activities: [
      'Criar papéis (admin, gerente comercial, financeiro, fiscal, operador WMS, viewer).',
      'Convidar usuários com o menor papel possível (princípio do menor privilégio).',
      'Definir alçadas de aprovação (compras, descontos comerciais, ajuste de estoque).',
      'Ativar MFA para papéis admin e financeiro.',
      'Testar RLS (row-level security): cada usuário só vê a empresa dele.',
    ],
    deliverable: 'Matriz de responsabilidades RACI + usuários ativos.',
    gate: 'Auditoria mostra que usuário operador não consegue ler dados de outra empresa.',
    modules: ['admin-usuarios', 'admin-seguranca', 'admin-parametros'],
  },
  {
    order: 4,
    code: 'F4',
    title: 'Fiscal & Certificado',
    goal: 'Habilitar emissão de NF-e e obrigações acessórias antes de vender.',
    duration: '2 a 4 dias',
    owner: 'Consultor + Contador',
    activities: [
      'Instalar certificado digital A1 (.pfx) na empresa.',
      'Configurar séries de NF-e/NFC-e por filial.',
      'Cadastrar tax_rules por UF/CFOP/NCM.',
      'Homologação em ambiente SEFAZ (rejeições esperadas até 100 emissões-teste).',
      'Simular DIFAL e ICMS-ST para operações interestaduais.',
      'Ativar geração de SPED Fiscal e SPED Contribuições.',
    ],
    deliverable: 'Primeira NF-e homologada e primeiro SPED validado no PVA.',
    gate: 'Contador aprova motor tributário com 3 cenários (venda dentro do estado, interestadual, ST).',
    modules: ['fiscal', 'contabilidade'],
  },
  {
    order: 5,
    code: 'F5',
    title: 'Estoque & Compras',
    goal: 'Ligar suprimentos e armazém antes do primeiro pedido comercial.',
    duration: '3 a 5 dias',
    owner: 'Consultor + Compras + Logística',
    activities: [
      'Cadastro de fornecedores homologados.',
      'Definição de política de estoque (mínimo, máximo, ponto de pedido).',
      'Inventário inicial: contagem física → ajuste único de saldo (com auditoria).',
      'Configuração de armazéns, ruas, endereços (WMS opcional na fase inicial).',
      'Fluxo de compra: requisição → cotação → aprovação → PO → recebimento.',
    ],
    deliverable: 'Estoque acurado, primeiro PO recebido no sistema.',
    gate: 'Acuracidade de inventário > 98% em amostra cega.',
    modules: ['estoque', 'compras', 'wms'],
  },
  {
    order: 6,
    code: 'F6',
    title: 'Comercial & PDV',
    goal: 'Habilitar a máquina de vender: preços, pipeline, faturamento.',
    duration: '3 a 5 dias',
    owner: 'Consultor + Comercial',
    activities: [
      'Tabela de preços por canal / segmento.',
      'Política de desconto e alçadas.',
      'Regras de crédito por cliente (limite, prazo médio, bloqueios).',
      'Configurar pipeline Kanban com etapas reais da empresa.',
      'Treinar equipe no fluxo: cliente → pedido → NF-e → AR.',
    ],
    deliverable: 'Primeiras 10 vendas reais processadas sem retrabalho.',
    gate: 'Ciclo O2C (order-to-cash) < 24h para pedidos padrão.',
    modules: ['comercial', 'fiscal', 'financeiro'],
  },
  {
    order: 7,
    code: 'F7',
    title: 'Financeiro & Conciliação',
    goal: 'Fechar o caixa todo dia. Conciliação diária vira rotina.',
    duration: '3 a 5 dias',
    owner: 'Consultor + Financeiro',
    activities: [
      'Importar posição atual de AP e AR (contas em aberto na virada).',
      'Configurar integração bancária (OFX manual ou Open Finance).',
      'Ativar cron de conciliação diária (06:00 UTC).',
      'Definir centros de custo para rateio.',
      'Configurar régua de cobrança (e-mail/WhatsApp automático).',
    ],
    deliverable: 'Extrato do dia D+1 conciliado com < 5% de exceções manuais.',
    gate: 'Fechamento de caixa diário em < 15 min.',
    modules: ['financeiro', 'contabilidade'],
  },
  {
    order: 8,
    code: 'F8',
    title: 'Produção / WMS avançado (se aplicável)',
    goal: 'Módulos operacionais pesados entram só depois que o básico está estável.',
    duration: '5 a 15 dias',
    owner: 'Consultor + PCP + Logística',
    activities: [
      'Cadastro de BOM e roteiros de produção.',
      'Primeira rodada de MRP com dados reais.',
      'Ondas de picking e putaway assistido no WMS.',
      'RFID / coletores quando aplicável.',
      'OEE inicial com metas conservadoras.',
    ],
    deliverable: 'Primeira OP concluída ponta a ponta + primeira onda WMS.',
    gate: 'Custo real da OP dentro de ±5% do custo padrão.',
    modules: ['producao', 'wms', 'rfid'],
  },
  {
    order: 9,
    code: 'F9',
    title: 'Go-live & Suporte hipercuidado',
    goal: 'Virar a chave em produção com sala de guerra ativa.',
    duration: '2 semanas',
    owner: 'Todos',
    activities: [
      'Congelamento de mudanças 72h antes do go-live.',
      'Sala de guerra presencial nos primeiros 5 dias úteis.',
      'Monitorar SLOs: latência de emissão de NF-e, erros de fila, backlog de aprovações.',
      'Postmortems curtos ao fim de cada dia da primeira semana.',
      'Reforço de treinamento pontual por persona.',
    ],
    deliverable: 'Operação em regime, com métricas dentro de SLA.',
    gate: 'Sponsor assina termo de aceite.',
    modules: ['dashboard', 'admin-seguranca'],
  },
  {
    order: 10,
    code: 'F10',
    title: 'Evolução contínua & IA',
    goal: 'Passa de "usar o ERP" para "o ERP trabalha para você".',
    duration: 'Contínuo',
    owner: 'Sponsor + IA Executiva',
    activities: [
      'Ativar Cérebro (IA Executiva) para análises e ações automáticas.',
      'Configurar autopilot 07:00 UTC (relatórios, alertas, reconciliações).',
      'Rodar auditorias de maturidade trimestrais.',
      'Instituir Review Loop mensal (KPIs + backlog de melhoria).',
      'Ativar módulos verticais adicionais conforme evolução do negócio.',
    ],
    deliverable: 'Roadmap trimestral aprovado com hipóteses e métricas.',
    gate: 'Ganho documentado (redução de tempo, aumento de margem, redução de erro).',
    modules: ['executivo', 'relatorios', 'crm-nps'],
  },
];
