import type { RoadmapPhase } from './foundation-types';

/**
 * Roteiro cronológico global de implantação de ERP.
 * Baseado em metodologia UEEF (Diagnóstico → Mapeamento → Desenho →
 * Implementação → Review Loop → Entrega) e boas práticas de mercado
 * (ASAP/Activate, Signature Method, Sure Step).
 */
export const IMPLEMENTATION_ROADMAP: RoadmapPhase[] = [
  {
    order: 1,
    code: 'F1',
    title: 'Fundação & Estrutura Organizacional',
    goal: 'Entender o negócio, mapear processos AS-IS e configurar o núcleo do ERP.',
    duration: '3 a 5 dias',
    owner: 'Consultor + Sponsor',
    activities: [
      'Kickoff com diretoria: escopo, cronograma e critérios de sucesso.',
      'Definição da Matriz e Filiais no módulo de Administração.',
      'Configuração do Modelo de Negócio (Atacado, Varejo ou Híbrido).',
      'Mapeamento de integrações bancárias e fiscais iniciais.',
      'Escolha das unidades piloto para implantação Wave 1.',
    ],
    deliverable: 'Estrutura organizacional ativada e Blueprint assinado.',
    gate: 'Sponsor aprova a hierarquia de empresas e filiais configurada.',
    modules: ['admin-empresas', 'admin-usuarios', 'admin-parametros'],
  },
  {
    order: 2,
    code: 'F2',
    title: 'Cadastros Mestres & Tax Engine',
    goal: 'Popular a espinha dorsal e configurar o motor tributário.',
    duration: '5 a 10 dias',
    owner: 'Consultor + Chave de cada área',
    activities: [
      'Importação de produtos, clientes e fornecedores.',
      'Configuração do Fiscal Vault (Certificado A1 e Senhas).',
      'Configuração de CFOPs, CSTs e regras tributárias automáticas.',
      'Bancos e contas correntes com saldos iniciais.',
      'Centros de custo e planos de contas.',
    ],
    deliverable: 'Bases mestres importadas e certificado A1 ativo no cofre.',
    gate: 'Certificado digital validado e motor fiscal pronto para emissão.',
    modules: ['admin-empresas', 'estoque', 'fiscal', 'contabilidade'],
  },
  {
    order: 3,
    code: 'F3',
    title: 'Segurança & RLS (Isolamento de Dados)',
    goal: 'Garantir que cada filial veja apenas seus dados e que o admin tenha visão global.',
    duration: '2 a 3 dias',
    owner: 'Consultor + TI',
    activities: [
      'Definição de papéis (Admin, Gerente de Filial, Operador WMS).',
      'Configuração de políticas RLS (Row-Level Security).',
      'Ativação de alçadas de aprovação financeira e comercial.',
      'Teste de estresse em permissões (tentativa de acesso cruzado).',
    ],
    deliverable: 'Matriz RACI ativada no sistema e políticas de isolamento validadas.',
    gate: 'Auditoria de segurança confirma que filiais não acessam dados mútuos.',
    modules: ['admin-usuarios', 'admin-seguranca'],
  },
  {
    order: 4,
    code: 'F4',
    title: 'WMS & Logística Inbound',
    goal: 'Habilitar o recebimento de mercadorias e armazenamento inteligente.',
    duration: '4 a 7 dias',
    owner: 'Consultor + Logística',
    activities: [
      'Mapeamento de armazéns, docas e endereços (ruas/níveis).',
      'Primeiro recebimento via WMS Operational Console.',
      'Configuração de regras de Putaway (onde guardar cada item).',
      'Treinamento de coletores de dados / RFID.',
    ],
    deliverable: 'Primeiro recebimento concluído com endereçamento automático.',
    gate: 'Acuracidade de endereçamento > 99% no piloto.',
    modules: ['wms', 'estoque'],
  },
  {
    order: 5,
    code: 'F5',
    title: 'Comercial, PDV & Vendas',
    goal: 'Habilitar canais de venda (Atacado/Representantes e Varejo/PDV).',
    duration: '5 a 8 dias',
    owner: 'Consultor + Comercial',
    activities: [
      'Tabelas de preço dinâmicas (Markup automático).',
      'Regras de crédito e integração com CRM.',
      'Configuração de PDV Offline para lojas físicas.',
      'Fluxo de Faturamento: Pedido → Separação → NF-e → Checkout.',
    ],
    deliverable: 'Primeira venda faturada com baixa automática no WMS.',
    gate: 'Fluxo Order-to-Cash (O2C) operando sem erros manuais.',
    modules: ['comercial', 'fiscal', 'pdv'],
  },
  {
    order: 6,
    code: 'F6',
    title: 'Produção & PCP (Indústria 4.0)',
    goal: 'Mapear fichas técnicas, roteiros e monitorar eficiência OEE.',
    duration: '10 a 20 dias',
    owner: 'Consultor + PCP',
    activities: [
      'Cadastro de BOM (Engenharia) e roteiros produtivos.',
      'Configuração do Kanban de Produção e Modo Guerra.',
      'Telemetria IoT para monitoramento de máquinas.',
      'Análise de OEE (Disponibilidade, Performance, Qualidade).',
    ],
    deliverable: 'Painel OEE em tempo real e rastreabilidade total de lotes.',
    gate: 'OPs custeadas com desvio < 3% do planejado.',
    modules: ['producao', 'pcp', 'iot'],
  },
  {
    order: 7,
    code: 'F7',
    title: 'Financeiro, Conciliação & DRE',
    goal: 'Garantir a saúde financeira e visibilidade de resultados.',
    duration: '5 a 10 dias',
    owner: 'Consultor + Financeiro',
    activities: [
      'Importação de saldos iniciais (AP/AR).',
      'Ativação de conciliação bancária via Open Finance.',
      'Configuração de DRE Gerencial por filial e consolidada.',
      'Gestão de fluxo de caixa projetado (30/60/90 dias).',
    ],
    deliverable: 'DRE Gerencial confiável e conciliação diária ativa.',
    gate: 'Fechamento financeiro diário concluído até as 09:00.',
    modules: ['financeiro', 'contabilidade'],
  },
  {
    order: 8,
    code: 'F8',
    title: 'Cérebro & Automação IA',
    goal: 'Deixar o ERP trabalhar por você via IA Executiva.',
    duration: 'Contínuo',
    owner: 'Sponsor + Digital Director',
    activities: [
      'Ativação do Native Brain (Cérebro Nativo) para decisões automáticas.',
      'Configuração de alertas proativos de estoque e crédito.',
      'Autopilot de reposição entre filiais (Smart Replenishment).',
      'Relatórios executivos via WhatsApp/E-mail diário.',
    ],
    deliverable: 'Gestão por exceção ativada (IA avisa o que precisa de ação).',
    gate: 'IA detecta e resolve autonomamente 20% dos gargalos operacionais.',
    modules: ['executivo', 'ia'],
  },
  {
    order: 9,
    code: 'F9',
    title: 'Auditoria & Sustentação',
    goal: 'Garantir a longevidade e compliance do sistema.',
    duration: '15 dias',
    owner: 'Consultor + Auditoria',
    activities: [
      'Execução do Security Audit (análise de vulnerabilidades).',
      'Checklist LGPD e Auditoria de Privacidade.',
      'Consolidação do Manual do Sistema personalizado.',
      'Treinamento de reciclagem por módulo.',
    ],
    deliverable: 'Certificado de Conformidade UEEF.',
    gate: 'Sistema operando com uptime > 99.9% e zero falhas de RLS.',
    modules: ['admin-seguranca', 'admin-manual'],
  },
  {
    order: 10,
    code: 'F10',
    title: 'Expansão & Novos Mercados',
    goal: 'Utilizar a base sólida para escalar o negócio.',
    duration: 'Contínuo',
    owner: 'Conselho Executivo',
    activities: [
      'Abertura de novas unidades com replicabilidade imediata.',
      'Ativação de Marketplace de Apps (Plugins).',
      'Customização de entidades via Metadata Configurator.',
      'Análise preditiva de demanda via Machine Learning.',
    ],
    deliverable: 'Ecossistema de negócios escalável.',
    gate: 'Novas filiais operando em < 24h após configuração básica.',
    modules: ['metadata', 'superadmin'],
  },
];
