export interface NavChild {
  title: string;
  href: string;
  icon: string;
}

export interface NavItem {
  title: string;
  href: string;
  icon: string;
  children?: NavChild[];
}

export interface NavSection {
  label?: string;
  items: NavItem[];
}

export const navigationSections: NavSection[] = [
  {
    label: 'Pacotes Verticais',
    items: [
      {
        title: 'Indústria Têxtil',
        href: '/vertical/textile',
        icon: 'Factory',
      },
      {
        title: 'Confecção & Moda',
        href: '/vertical/apparel',
        icon: 'Scissors',
      },
      {
        title: 'Fiação & Fios',
        href: '/vertical/spinning',
        icon: 'Repeat',
      },
      {
        title: 'Tecelagem',
        href: '/vertical/weaving',
        icon: 'Columns',
      },
      {
        title: 'Alimentos & Rações',
        href: '/vertical/food-feed',
        icon: 'Database',
      },
      {
        title: 'Farmacêutico',
        href: '/vertical/pharma',
        icon: 'ShieldCheck',
      },
      {
        title: 'Distribuição & Atacado',
        href: '/vertical/distribution',
        icon: 'Truck',
      },
      {
        title: 'Varejo & Redes',
        href: '/vertical/retail',
        icon: 'ShoppingBag',
      },
      {
        title: 'Franquias',
        href: '/vertical/franchise',
        icon: 'Building2',
      },
      {
        title: 'Holdings & Grupos',
        href: '/vertical/holding',
        icon: 'FolderTree',
      },
    ],
  },
  {
    label: 'Dashboard',
    items: [
      {
        title: 'Dashboard',
        href: '/dashboard',
        icon: 'LayoutDashboard',
      },
      {
        title: '🧠 IA Executiva',
        href: '/executive/executive',
        icon: 'Brain',
      },
      {
        title: '💚 Use Success',
        href: '/success',
        icon: 'Heart',
      },
      {
        title: '🧠 Cérebro Nativo',
        href: '/executive/brain',
        icon: 'Sparkles',
      },
    ],
  },
  {
    label: 'Operacional',
    items: [
      {
        title: 'Fluxo Operacional',
        href: '/operacional',
        icon: 'ArrowRightLeft',
        children: [
          { title: 'Dashboard Operacional', href: '/operacional/dashboard', icon: 'BarChart3' },
          { title: 'Acompanhamento', href: '/operacional/rastreamento', icon: 'Eye' },
          { title: 'Separação', href: '/operacional/separacao', icon: 'PackageSearch' },
          { title: 'Conferência', href: '/operacional/conferencia', icon: 'ClipboardCheck' },
          { title: 'Faturamento', href: '/operacional/faturamento', icon: 'FileText' },
          { title: 'Expedição', href: '/operacional/expedicao', icon: 'Truck' },
        ],
      },
      {
        title: 'Comercial',
        href: '/comercial',
        icon: 'Users',
        children: [
          { title: 'CRM Enterprise', href: '/comercial/crm', icon: 'Target' },
          { title: 'Dashboard', href: '/comercial/dashboard', icon: 'BarChart3' },
          { title: '🛒 Painel Único (PDV)', href: '/comercial/pdv', icon: 'ShoppingCart' },
          { title: '⚡ O Que Fazer Hoje', href: '/comercial/execucao', icon: 'Zap' },
          { title: 'Painel Vendedor', href: '/comercial/vendedor', icon: 'Zap' },
          { title: 'Funil Comercial', href: '/comercial/funil', icon: 'Filter' },
          { title: 'Clientes', href: '/comercial/clientes', icon: 'UserCircle' },
          { title: 'Perfil Comercial', href: '/comercial/perfil-clientes', icon: 'Crown' },
          { title: 'Representantes', href: '/comercial/representantes', icon: 'UserCheck' },
          
          { title: 'Pedidos', href: '/comercial/pedidos', icon: 'ClipboardList' },
          { title: 'Orçamentos', href: '/comercial/orcamentos', icon: 'FileText' },
          { title: 'Comissões', href: '/comercial/comissoes', icon: 'DollarSign' },
          { title: 'Metas', href: '/comercial/metas', icon: 'Target' },
          { title: 'Forecast', href: '/comercial/forecast', icon: 'TrendingUp' },
          { title: 'Campanhas', href: '/comercial/campanhas', icon: 'Megaphone' },
          { title: 'Performance', href: '/comercial/performance', icon: 'BarChart3' },
          { title: 'Relatório Vendas × Canal', href: '/comercial/relatorio-canal', icon: 'FileBarChart' },
          { title: '📘 Playbook', href: '/comercial/playbook', icon: 'BookOpen' },
          { title: '🎮 Gamificação', href: '/comercial/gamificacao', icon: 'Trophy' },
          { title: '🧠 IA Comercial', href: '/comercial/ia', icon: 'Brain' },
          { title: '🤖 Automação', href: '/comercial/automacao', icon: 'Bot' },
        ],
      },
      {
        title: 'Relacionamento',
        href: '/relacionamento',
        icon: 'Heart',
        children: [
          { title: 'NPS · Dashboard', href: '/relacionamento/nps/dashboard', icon: 'BarChart3' },
          { title: 'Campanhas', href: '/relacionamento/nps/campanhas', icon: 'Megaphone' },
          { title: 'Pesquisas', href: '/relacionamento/nps/pesquisas', icon: 'ClipboardList' },
          { title: 'Convites', href: '/relacionamento/nps/convites', icon: 'Send' as any },
          { title: 'Respostas', href: '/relacionamento/nps/respostas', icon: 'MessageSquare' as any },
          { title: 'Relatórios', href: '/relacionamento/nps/relatorios', icon: 'FileText' },
          { title: 'Templates', href: '/relacionamento/nps/templates', icon: 'Palette' as any },
          { title: 'Automações', href: '/relacionamento/nps/automacoes', icon: 'Zap' },
          { title: 'Configurações', href: '/relacionamento/nps/configuracoes', icon: 'Settings' },
        ],
      },
      {
        title: 'Compras',
        href: '/compras',
        icon: 'ShoppingCart',
        children: [
          { title: 'Fornecedores', href: '/compras/fornecedores', icon: 'Building2' },
          { title: 'Pedidos de Compra', href: '/compras/pedidos', icon: 'ClipboardList' },
          { title: 'Cotações', href: '/compras/cotacoes', icon: 'FileSearch' },
        ],
      },
      {
        title: 'Produção',
        href: '/producao',
        icon: 'Factory',
        children: [
          { title: 'Dashboard Industrial', href: '/producao/dashboard-industrial', icon: 'Gauge' },
          { title: 'Painel PCP', href: '/producao/pcp', icon: 'BarChart3' },
          { title: 'Ordens de Produção', href: '/producao/ordens', icon: 'ClipboardCheck' },
          { title: '📋 Kanban', href: '/producao/kanban', icon: 'Columns' },
          { title: '🏭 Terceirização', href: '/producao/terceirizacao', icon: 'Truck' },
          { title: 'Fila de Produção', href: '/producao/fila', icon: 'ListOrdered' },
          { title: 'Agendamento', href: '/producao/programacao', icon: 'CalendarClock' },
          { title: 'Chão de Fábrica', href: '/producao/chao-de-fabrica', icon: 'Activity' },
          { title: '📲 Terminal Operador', href: '/producao/terminal', icon: 'Smartphone' },
          { title: 'Apontamentos', href: '/producao/apontamento', icon: 'Timer' },
          { title: 'Setores', href: '/producao/setores', icon: 'Building2' },
          { title: '📏 Linhas Produtivas', href: '/producao/linhas', icon: 'Rows3' },
          { title: '🔧 Recursos', href: '/producao/recursos', icon: 'Wrench' },
          { title: '🗺️ Rotas Produtivas', href: '/producao/roteiros', icon: 'Route' },
          { title: 'Etapas Produtivas', href: '/producao/etapas', icon: 'Layers' },
          { title: '📄 Fichas Técnicas', href: '/producao/fichas', icon: 'FileText' },
          { title: '⚡ Capacidade', href: '/producao/capacidade', icon: 'Zap' },
          { title: 'Controle de Qualidade', href: '/producao/qualidade', icon: 'ShieldCheck' },
          { title: '🔍 Rastreabilidade', href: '/producao/rastreabilidade', icon: 'Search' },
          { title: '📦 MRP', href: '/producao/mrp', icon: 'Package' },
          { title: 'Estoque de Insumos', href: '/producao/insumos', icon: 'Boxes' },
          { title: 'Consumo MP', href: '/producao/consumo', icon: 'PackageMinus' },
          { title: 'Custo e Lucro', href: '/producao/custos', icon: 'Calculator' },
          { title: '📊 BI Industrial', href: '/producao/bi', icon: 'PieChart' },
          { title: '📊 OEE', href: '/producao/oee', icon: 'CircleGauge' },
          { title: '🧠 IA Produção', href: '/producao/ia', icon: 'Brain' },
          { title: '🤖 ML Predições', href: '/producao/previsoes', icon: 'Sparkles' },
          { title: '🔮 Digital Twin', href: '/producao/twin', icon: 'Cpu' },
          { title: '🚀 APS', href: '/producao/aps', icon: 'Rocket' },
          { title: '🌐 IoT Monitor', href: '/producao/iot', icon: 'Wifi' },
        ],
      },
      {
        title: 'Estoque',
        href: '/estoque',
        icon: 'Package',
        children: [
          { title: 'Produtos', href: '/estoque/produtos', icon: 'Box' },
          { title: 'Categorias', href: '/estoque/categorias', icon: 'FolderTree' },
          { title: 'Movimentações', href: '/estoque/movimentacoes', icon: 'ArrowLeftRight' },
          { title: 'Kardex', href: '/estoque/kardex', icon: 'BookOpen' },
          { title: 'Saldos', href: '/estoque/saldos', icon: 'Calculator' },
        ],
      },
    ],
  },
  {
    label: 'Financeiro',
    items: [
      {
        title: 'Financeiro',
        href: '/financeiro',

        icon: 'Wallet',
        children: [
          { title: 'Central Financeira', href: '/financeiro/central', icon: 'Zap' },
          { title: 'Dashboard', href: '/financeiro/dashboard', icon: 'BarChart3' },
          { title: 'Contas a Pagar', href: '/financeiro/pagar', icon: 'ArrowUpCircle' },
          { title: 'Contas a Receber', href: '/financeiro/receber', icon: 'ArrowDownCircle' },
          { title: 'Conta Corrente', href: '/financeiro/conta-corrente', icon: 'Users' },
          { title: 'Compensação', href: '/financeiro/compensacao', icon: 'ArrowLeftRight' },
          { title: 'Régua de Cobrança', href: '/financeiro/cobranca-automatica', icon: 'BellRing' },
          { title: 'Recorrências', href: '/financeiro/recorrencias', icon: 'RotateCw' },
          { title: 'Inadimplência', href: '/financeiro/inadimplencia', icon: 'AlertOctagon' },
          { title: 'Cenários de Caixa', href: '/financeiro/cenarios', icon: 'GitBranch' },
          { title: 'Alertas Inteligentes', href: '/financeiro/alertas', icon: 'Siren' },
          { title: 'DRE Dinâmica', href: '/financeiro/dre-dinamica', icon: 'BarChart3' },
          { title: 'Fluxo de Caixa', href: '/financeiro/fluxo', icon: 'TrendingUp' },
          { title: 'DRE (Ledger)', href: '/financeiro/dre', icon: 'LineChart' },
          { title: 'Varejo × Atacado', href: '/financeiro/segmentado', icon: 'Split' },
          { title: 'Tesouraria', href: '/financeiro/tesouraria', icon: 'Building2' },
          { title: 'Adiantamentos', href: '/financeiro/adiantamentos', icon: 'Wallet' },
          { title: 'Centros de Custo', href: '/financeiro/centros-custo', icon: 'FolderTree' },
          { title: 'Renegociações', href: '/financeiro/renegociacoes', icon: 'RefreshCw' },
          { title: 'Conciliação', href: '/financeiro/conciliacao', icon: 'CheckCircle' },
          { title: 'Conciliação por Canal', href: '/financeiro/conciliacao-canal', icon: 'Split' },
          { title: 'Cobranças PIX', href: '/financeiro/pix', icon: 'QrCode' },
          { title: 'Boletos', href: '/financeiro/boletos', icon: 'Receipt' },
          { title: 'Cheques', href: '/financeiro/cheques', icon: 'FileCheck' },
          { title: 'Inteligência IA', href: '/financeiro/inteligencia', icon: 'Brain' },
          { title: 'BI Executivo', href: '/financeiro/bi', icon: 'BarChart3' },
          { title: 'Antifraude', href: '/financeiro/antifraude', icon: 'ShieldAlert' },
          { title: 'Importar Extrato', href: '/financeiro/importar-extrato', icon: 'Upload' },
          { title: 'Auditoria Contínua', href: '/financeiro/auditoria', icon: 'ShieldCheck' },
        ],
      },
      {
        title: 'Crédito & Risco',
        href: '/credito',
        icon: 'ShieldCheck',
        children: [
          { title: 'Dashboard Risco', href: '/credito/dashboard', icon: 'BarChart3' },
          { title: 'Análise de Crédito', href: '/credito/analise', icon: 'Shield' },
          { title: 'Bloqueios', href: '/credito/bloqueios', icon: 'Lock' },
          { title: 'Cobrança', href: '/credito/cobranca', icon: 'Phone' },
        ],
      },
      {
        title: 'Contabilidade',
        href: '/contabilidade',
        icon: 'Calculator',
        children: [
          { title: 'Painel Executivo', href: '/contabilidade/painel', icon: 'BarChart3' },
          { title: 'Plano de Contas', href: '/contabilidade/plano-contas', icon: 'FolderTree' },
          { title: 'Lançamentos', href: '/contabilidade/lancamentos', icon: 'FileText' },
          { title: 'Razão Contábil', href: '/contabilidade/razao', icon: 'BookOpen' },
          { title: 'Balancete', href: '/contabilidade/balancete', icon: 'Scale' },
          { title: 'DRE', href: '/contabilidade/dre', icon: 'TrendingUp' },
          { title: 'Balanço Patrimonial', href: '/contabilidade/balanco', icon: 'Building2' },
          { title: 'Fechamento Contábil', href: '/contabilidade/fechamento', icon: 'Lock' },
        ],
      },
      {
        title: 'Fiscal',
        href: '/fiscal',
        icon: 'FileCheck',
        children: [
          { title: 'Painel Fiscal', href: '/fiscal/dashboard', icon: 'Gauge' },
          { title: 'NF-e', href: '/fiscal/nfe', icon: 'FileText' },
          { title: 'NFC-e', href: '/fiscal/nfce', icon: 'Receipt' },
          { title: 'CT-e', href: '/fiscal/cte', icon: 'FileCheck2' },
          { title: 'MDF-e', href: '/fiscal/mdfe', icon: 'ScrollText' },
          { title: 'Regras Fiscais', href: '/fiscal/regras-fiscais', icon: 'Sliders' },
          { title: 'ICMS ST', href: '/fiscal/icms-st', icon: 'Percent' },
          { title: 'DIFAL', href: '/fiscal/difal', icon: 'Globe' },
          { title: 'SPED Fiscal/Contrib.', href: '/fiscal/sped', icon: 'FileDown' },
          { title: 'EFD-Reinf', href: '/fiscal/reinf', icon: 'FileBadge' },
          { title: 'Relatórios Fiscais', href: '/fiscal/relatorios', icon: 'PieChart' },
        ],
      },
    ],
  },
  {
    label: 'Logística',
    items: [
      {
        title: 'WMS',
        href: '/wms',
        icon: 'Warehouse',
        children: [
          { title: 'Dashboard WMS', href: '/wms/dashboard', icon: 'LayoutDashboard' },
          { title: 'Analytics & SLA', href: '/wms/analytics', icon: 'Gauge' },
          { title: 'Centros de Distrib.', href: '/wms/centros-distribuicao', icon: 'Building2' },
          { title: 'Armazenagem', href: '/wms/armazenagem', icon: 'Boxes' },
          { title: 'Endereços', href: '/wms/enderecos', icon: 'MapPin' },
          { title: 'Saldos', href: '/wms/saldos', icon: 'Database' },
          { title: 'Matriz Multi-Loja', href: '/wms/matriz-estoque', icon: 'LayoutGrid' },
          { title: 'Transferências entre Canais', href: '/wms/transferencias-canal', icon: 'ArrowRightLeft' },
          { title: 'Relatório Estoque × Canal', href: '/wms/relatorio-estoque-canal', icon: 'FileBarChart' },
          { title: 'Auditoria de Estoque', href: '/wms/auditoria-estoque', icon: 'ClipboardList' },
          { title: 'Reconciliação Fat. × Saída', href: '/wms/reconciliacao-faturamento', icon: 'Scale' },
          { title: 'Alocação de SKU', href: '/wms/alocacao', icon: 'Move' },
          { title: 'Lotes', href: '/wms/lotes', icon: 'Layers' },
          { title: 'Recebimento', href: '/wms/recebimento', icon: 'PackagePlus' },
          { title: 'Put-Away', href: '/wms/putaway', icon: 'ArrowDown' },
          { title: 'Ressuprimento', href: '/wms/ressuprimento', icon: 'RefreshCw' },
          { title: 'Reservas de Pedido', href: '/wms/reservas', icon: 'Bookmark' },
          { title: 'Separação (Picking)', href: '/wms/separacao', icon: 'PackageSearch' },
          { title: 'Separação de Pedidos', href: '/wms/separacao-pedidos', icon: 'ListChecks' },
          { title: 'Rota de Picking', href: '/wms/rota-picking', icon: 'Route' },
          { title: 'Ondas', href: '/wms/ondas', icon: 'Layers' },
          { title: 'Wave Planning v2', href: '/wms/wave-planning', icon: 'Waves' },
          { title: 'Embalagem (Packing)', href: '/wms/embalagem', icon: 'PackageCheck' },
          { title: 'Conferência', href: '/wms/conferencia', icon: 'ScanBarcode' },
          { title: 'Cross-Docking', href: '/wms/cross-docking', icon: 'Shuffle' },
          { title: 'Montagem de Kits', href: '/wms/kits', icon: 'Boxes' },
          { title: 'Docas', href: '/wms/docas', icon: 'DoorOpen' },
          { title: 'Agenda de Docas', href: '/wms/agenda-docas', icon: 'CalendarClock' },
          { title: 'Pátio (Yard)', href: '/wms/yard', icon: 'ParkingSquare' },
          { title: 'Expedição', href: '/wms/expedicao', icon: 'Truck' },
          { title: 'Scorecard Transp.', href: '/wms/scorecard-transportadoras', icon: 'Trophy' },
          { title: 'Devoluções', href: '/wms/devolucoes', icon: 'RotateCcw' },
          { title: 'Qualidade & Quarentena', href: '/wms/qualidade', icon: 'ShieldCheck' },
          { title: 'Inventário', href: '/wms/inventario', icon: 'ClipboardList' },
          { title: 'Inventário Cíclico', href: '/wms/inventario-ciclico', icon: 'ClipboardCheck' },
          { title: 'Movimentações', href: '/wms/movimentacoes', icon: 'MoveHorizontal' },
          { title: 'Mão de Obra', href: '/wms/mao-de-obra', icon: 'Users' },
          { title: 'Slotting', href: '/wms/slotting', icon: 'Grid3x3' },
          { title: 'Digital Twin 3D', href: '/wms/twin', icon: 'Box' },
          { title: 'Inteligência ML', href: '/wms/inteligencia', icon: 'Sparkles' },
          { title: 'Faturamento 3PL', href: '/wms/faturamento-3pl', icon: 'DollarSign' },
          { title: 'IA WMS', href: '/wms/ia', icon: 'Brain' },
        ],
      },
      {
        title: 'RFID',
        href: '/rfid',
        icon: 'Radio',
        children: [
          { title: 'Dashboard RFID', href: '/rfid/dashboard', icon: 'LayoutDashboard' },
          { title: 'Leitores', href: '/rfid/leitores', icon: 'Wifi' },
          { title: 'Tags', href: '/rfid/tags', icon: 'Tag' },
          { title: 'Eventos', href: '/rfid/eventos', icon: 'Activity' },
          { title: 'Integração WMS', href: '/rfid/integracao', icon: 'ArrowLeftRight' },
        ],
      },
      {
        title: 'TMS - Transporte',
        href: '/tms',
        icon: 'Truck',
        children: [
          { title: 'Dashboard TMS', href: '/tms/dashboard', icon: 'LayoutDashboard' },
          { title: 'Transportadoras', href: '/tms/transportadoras', icon: 'Building2' },
          { title: 'Veículos / Frota', href: '/tms/veiculos', icon: 'Truck' },
          { title: 'Rotas de Entrega', href: '/tms/rotas', icon: 'MapPin' },
          { title: 'Rastreamento ao Vivo', href: '/tms/live', icon: 'Navigation' },
          { title: 'Comprovantes', href: '/tms/comprovantes', icon: 'FileCheck' },
        ],
      },
    ],
  },
  {
    label: 'Gestão',
    items: [
      {
        title: 'Relatórios',
        href: '/relatorios',
        icon: 'BarChart3',
        children: [
          { title: 'Vendas', href: '/relatorios/vendas', icon: 'ShoppingBag' },
          { title: 'Estoque', href: '/relatorios/estoque', icon: 'Package' },
          { title: 'Financeiro', href: '/relatorios/financeiro', icon: 'Wallet' },
          { title: 'Produção', href: '/relatorios/producao', icon: 'Factory' },
        ],
      },
      {
        title: 'Administração',
        href: '/admin',
        icon: 'Settings',
        children: [
          { title: 'Usuários', href: '/admin/usuarios', icon: 'Users' },
          { title: 'Empresas', href: '/admin/empresas', icon: 'Building' },
          { title: 'Parâmetros', href: '/admin/parametros', icon: 'Sliders' },
          { title: 'Relatório Diário', href: '/admin/relatorio-diario', icon: 'FileText' },
          { title: 'Auditoria Cross-Módulos', href: '/admin/auditoria-cross', icon: 'Activity' },
          { title: 'Auditoria Crítica (Imutável)', href: '/admin/auditoria-critica', icon: 'ShieldAlert' },
          { title: 'Metadata Engine', href: '/admin/metadata', icon: 'Database' },
          { title: 'Workflow Engine', href: '/admin/workflows', icon: 'GitBranch' },
          { title: 'Caixa de Workflows', href: '/workflows/inbox', icon: 'Inbox' },

          { title: 'Automation Engine', href: '/admin/automacoes', icon: 'Zap' },
          { title: 'Dashboard Engine', href: '/admin/dashboards', icon: 'LayoutDashboard' },
          { title: 'Auditoria de Segurança', href: '/admin/seguranca/auditoria', icon: 'ShieldAlert' },
          { title: 'Manual do Sistema', href: '/admin/manual', icon: 'BookOpenCheck' },
        ],
      },
    ],
  },
];

// Flat list for backward compatibility
export const navigationItems = navigationSections.flatMap((s) => s.items);
