// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado no ERP (id, email, client_id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function userClient(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_products_default = defineTool2({
  name: "search_products",
  title: "Buscar produtos",
  description: "Lista produtos do estoque do usu\xE1rio. Filtra por termo (nome/SKU) e retorna at\xE9 `limit` resultados. Respeita RLS multi-tenant.",
  inputSchema: {
    query: z.string().trim().optional().describe("Termo de busca por nome ou SKU."),
    limit: z.number().int().positive().max(50).optional().describe("M\xE1ximo de resultados (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = userClient(ctx);
    const max = limit ?? 20;
    let q = supabase.from("products").select("id, sku, name, unit, sale_price, stock_quantity").limit(max);
    if (query && query.length > 0) {
      const term = `%${query}%`;
      q = q.or(`name.ilike.${term},sku.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-payables.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function userClient2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_payables_default = defineTool3({
  name: "list_payables",
  title: "Contas a pagar",
  description: "Lista t\xEDtulos financeiros a pagar (accounts_payable). Filtra por status ('open', 'paid', 'overdue') e retorna at\xE9 `limit` registros ordenados por vencimento.",
  inputSchema: {
    status: z2.enum(["open", "paid", "overdue"]).optional().describe("Filtra pelo status do t\xEDtulo."),
    limit: z2.number().int().positive().max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = userClient2(ctx);
    let q = supabase.from("accounts_payable").select("id, description, supplier_name, amount, due_date, status").order("due_date", { ascending: true }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const total = (data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    return {
      content: [
        {
          type: "text",
          text: `Encontrados ${data?.length ?? 0} t\xEDtulos (soma R$ ${total.toFixed(2)})

${JSON.stringify(
            data ?? [],
            null,
            2
          )}`
        }
      ],
      structuredContent: { rows: data ?? [], count: data?.length ?? 0, total_amount: total }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "arcuhqdiydlvekanychw";
var mcp_default = defineMcp({
  name: "use-sistemas-erp-mcp",
  title: "Use Sistemas ERP",
  version: "0.1.0",
  instructions: "Ferramentas do ERP Use Sistemas (multi-tenant, RLS por empresa). Use `whoami` para confirmar o usu\xE1rio conectado. Use `search_products` para consultar o cadastro de produtos. Use `list_payables` para revisar contas a pagar por status e vencimento. Todas as consultas respeitam o escopo de empresa do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, search_products_default, list_payables_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
