import { Users, Building2, Settings, ShieldCheck, CreditCard } from 'lucide-react';
import { commonScreens, type ModuleManual } from '../content-types';

export const ADMINISTRACAO_MODULES: ModuleManual[] = [
  {
    slug: 'admin-usuarios',
    title: 'Usuários & Permissões',
    category: 'Administração',
    icon: Users,
    short: 'Cadastro de usuários, papéis (RBAC) e permissões granulares.',
    overview: ['Gestão de usuários com papéis (admin, manager, operator, viewer + verticais) e permissões por recurso/ação.'],
    routes: [{ label: 'Usuários', path: '/admin/usuarios' }],
    personas: ['Administrador'],
    prerequisites: ['Empresa configurada'],
    steps: [
      { title: 'Convidar usuário', description: 'Usuários → Novo → e-mail + papel inicial.' },
      { title: 'Atribuir permissões', description: 'Papéis já vêm com permissões padrão; ajuste granular por usuário se necessário.' },
      { title: 'Auditar mudanças', description: 'Toda alteração de papel é logada em system_audit_logs.' },
    ],
    sections: [{ heading: 'Segurança', paragraphs: ['Papéis nunca são armazenados no profile — sempre em user_roles com função has_role(). Nunca conceda admin sem MFA.'] }],
    faq: [{ q: 'Usuário não vê módulo?', a: 'Cheque papel e se o módulo está no plano contratado.' }],
    troubleshooting: [{ problem: 'Convite não recebido', solution: 'Reenvie e valide spam/domínio de e-mail.' }],
    screenshots: commonScreens(['Lista de usuários', 'Editor de papel']),
  },
  {
    slug: 'admin-empresas',
    title: 'Empresas & Filiais',
    category: 'Administração',
    icon: Building2,
    short: 'Multi-empresa, filiais, regime tributário e dados fiscais.',
    overview: ['Gerencie matriz e filiais com dados fiscais, regime e endereços.'],
    routes: [{ label: 'Empresas', path: '/admin/empresas' }],
    personas: ['Administrador', 'Fiscal'],
    prerequisites: [],
    steps: [
      { title: 'Cadastrar matriz', description: 'Empresas → Nova → CNPJ (autofill BrasilAPI).' },
      { title: 'Adicionar filiais', description: 'Vincule à matriz; cada filial pode ter regime próprio.' },
      { title: 'Ativar/inativar', description: 'Inativar bloqueia lançamentos mas preserva histórico.' },
    ],
    sections: [],
    faq: [{ q: 'Trocar de empresa?', a: 'Use o seletor no topo (multi-tenant).' }],
    troubleshooting: [{ problem: 'CNPJ inválido', solution: 'Confirme dígitos verificadores; consulte Receita.' }],
    screenshots: commonScreens(['Lista de empresas', 'Ficha da empresa']),
  },
  {
    slug: 'admin-parametros',
    title: 'Parâmetros do Sistema',
    category: 'Administração',
    icon: Settings,
    short: 'Configurações por categoria: fiscal, comercial, financeiro, WMS, integrações.',
    overview: ['Parâmetros globais e por empresa que ajustam comportamento sem código.'],
    routes: [{ label: 'Parâmetros', path: '/admin/parametros' }],
    personas: ['Administrador'],
    prerequisites: [],
    steps: [
      { title: 'Filtrar por categoria', description: 'Escolha Fiscal, Financeiro, etc.' },
      { title: 'Editar valor', description: 'Alterações sensíveis exigem confirmação e ficam auditadas.' },
    ],
    sections: [],
    faq: [{ q: 'Onde altero e-mail padrão?', a: 'Categoria Integrações → parâmetros de e-mail.' }],
    troubleshooting: [{ problem: 'Parâmetro não aplica', solution: 'Alguns exigem re-login para atualizar cache.' }],
    screenshots: commonScreens(['Lista de parâmetros', 'Edição']),
  },
  {
    slug: 'admin-seguranca',
    title: 'Segurança & Auditoria',
    category: 'Administração',
    icon: ShieldCheck,
    short: 'Auditoria cross-módulo, eventos críticos e scan de segurança.',
    overview: ['Trilha completa de eventos críticos (DELETE, ROLE_CHANGE, LOGIN_FAILED, EXPORT) e revisão contínua.'],
    routes: [
      { label: 'Auditoria', path: '/admin/auditoria' },
      { label: 'Auditoria Segurança', path: '/admin/seguranca/auditoria' },
    ],
    personas: ['Administrador', 'Compliance'],
    prerequisites: [],
    steps: [
      { title: 'Filtrar eventos', description: 'Por módulo, ação, usuário, período.' },
      { title: 'Investigar', description: 'Compare old_data vs new_data para reconstituir alterações.' },
      { title: 'Exportar', description: 'Gere relatório para compliance/auditoria externa.' },
    ],
    sections: [{ heading: 'Boas práticas', paragraphs: ['Revise semanalmente eventos ROLE_CHANGE e DELETE.'] }],
    faq: [{ q: 'Faltam eventos?', a: 'Confirme triggers ativos e RLS de leitura.' }],
    troubleshooting: [{ problem: 'Export bloqueado', solution: 'Requer papel admin + confirmação.' }],
    screenshots: commonScreens(['Trilha de auditoria', 'Detalhe de evento']),
  },
  {
    slug: 'billing',
    title: 'Billing & Uso',
    category: 'Administração',
    icon: CreditCard,
    short: 'Plano contratado, medidores de uso e upgrades.',
    overview: ['Acompanhe consumo por medidor (usuários, NF-e, ordens, IA) e faça upgrade quando necessário.'],
    routes: [
      { label: 'Uso', path: '/billing/uso' },
      { label: 'Upgrade', path: '/upgrade' },
    ],
    personas: ['Administrador', 'Diretor'],
    prerequisites: [],
    steps: [
      { title: 'Ver consumo', description: 'Uso mostra % de cada medidor no mês.' },
      { title: 'Upgrade', description: 'Escolha plano superior; efeito imediato.' },
    ],
    sections: [],
    faq: [{ q: 'Bloqueio por limite?', a: 'Sistema alerta em 80% e bloqueia em 100% — planeje upgrade antes.' }],
    troubleshooting: [{ problem: 'Fatura não bate', solution: 'Contate suporte com número da fatura.' }],
    screenshots: commonScreens(['Medidores', 'Planos']),
  },
];
