import { ShoppingCart, Factory, Warehouse, Truck, Package, Boxes, Radio } from 'lucide-react';
import { commonScreens, type ModuleManual } from '../content-types';

export const OPERACIONAL_MODULES: ModuleManual[] = [
  {
    slug: 'comercial',
    title: 'Comercial & Vendas',
    category: 'Operacional',
    icon: ShoppingCart,
    short: 'Pipeline de vendas, pedidos, clientes e automação com IA.',
    overview: [
      'O módulo Comercial gerencia todo o ciclo B2B/B2C: cadastro de clientes, propostas, pedidos, pipeline Kanban e faturamento.',
      'Integra-se automaticamente com Estoque (reserva), Fiscal (NF-e) e Financeiro (contas a receber).',
    ],
    routes: [
      { label: 'Clientes', path: '/comercial/clientes' },
      { label: 'Pedidos', path: '/comercial/pedidos' },
      { label: 'Pipeline', path: '/comercial/pipeline' },
    ],
    personas: ['Comercial', 'Gerente de Vendas', 'Diretor'],
    prerequisites: ['Cadastro de produtos ativo', 'Tabela de preços configurada', 'Módulo Fiscal para emissão de NF-e'],
    steps: [
      { title: 'Cadastrar cliente', description: 'Vá em Comercial → Clientes → Novo. Informe CNPJ e o sistema busca dados via BrasilAPI.' },
      { title: 'Criar pedido', description: 'Em Pedidos → Novo, selecione cliente, adicione itens, revise impostos calculados automaticamente.' },
      { title: 'Acompanhar no pipeline', description: 'Arraste o card entre colunas (Prospect → Proposta → Fechado). Cada mudança é auditada.' },
      { title: 'Faturar', description: 'Ao mover para "Faturamento", o sistema gera a NF-e e o AR automaticamente.', tip: 'Confira o CFOP sugerido pelo motor fiscal antes de emitir.' },
    ],
    sections: [
      { heading: 'Automação com IA', paragraphs: ['O assistente de vendas sugere próximos passos, produtos complementares e detecta risco de churn.'] },
      { heading: 'Gamificação', paragraphs: ['Ranking e badges motivam a equipe. Configure metas mensais em Parâmetros.'] },
    ],
    faq: [
      { q: 'Cliente não aparece na busca?', a: 'Verifique se está ativo e se pertence à empresa selecionada no topo.' },
      { q: 'Como conceder desconto?', a: 'Descontos acima da alçada geram workflow de aprovação automático.' },
    ],
    troubleshooting: [
      { problem: 'Pedido não fatura', solution: 'Confirme estoque disponível, limite de crédito do cliente e certificado NF-e válido.' },
    ],
    screenshots: commonScreens(['Lista de clientes', 'Novo pedido — itens', 'Pipeline Kanban']),
  },
  {
    slug: 'producao',
    title: 'Produção (PCP)',
    category: 'Operacional',
    icon: Factory,
    short: 'Ordens de produção, MRP, OEE, apontamentos e Kanban de chão de fábrica.',
    overview: [
      'PCP completo: BOM, roteiro, MRP, ordens, apontamentos em tempo real, cálculo de OEE e Kanban por centro de trabalho.',
    ],
    routes: [
      { label: 'Ordens de Produção', path: '/producao/ordens' },
      { label: 'BOM', path: '/producao/bom' },
      { label: 'MRP', path: '/producao/mrp' },
    ],
    personas: ['Produção', 'PCP', 'Gerente Industrial'],
    prerequisites: ['Produtos com BOM cadastrada', 'Centros de trabalho definidos'],
    steps: [
      { title: 'Cadastrar BOM', description: 'Produção → BOM → Novo. Adicione componentes, quantidades e perdas.' },
      { title: 'Rodar MRP', description: 'MRP → Rodar. O sistema sugere ordens de compra e produção com base em demanda + estoque.' },
      { title: 'Abrir OP', description: 'Ordens → Nova → escolha produto, quantidade e data. Materiais são reservados.' },
      { title: 'Apontar produção', description: 'No terminal de chão de fábrica, operador aponta início/fim, quantidade e refugo.' },
    ],
    sections: [
      { heading: 'OEE', paragraphs: ['Calculado automaticamente a partir dos apontamentos (Disponibilidade × Performance × Qualidade).'] },
    ],
    faq: [{ q: 'MRP não sugere nada?', a: 'Verifique previsão de vendas e leadtime dos itens.' }],
    troubleshooting: [
      { problem: 'Ordem trava em "Aguardando material"', solution: 'Falta estoque de componente — cheque no MRP ou libere via compra emergencial.' },
    ],
    screenshots: commonScreens(['Lista de OPs', 'BOM', 'Kanban chão de fábrica']),
  },
  {
    slug: 'wms',
    title: 'WMS — Armazém',
    category: 'Operacional',
    icon: Warehouse,
    short: 'Recebimento, endereçamento, picking, packing e inventário rotativo.',
    overview: [
      'Gestão de múltiplos CDs, entradas, put-away, ondas de picking, packing e expedição. Suporta RFID e coletores.',
    ],
    routes: [
      { label: 'Recebimento', path: '/wms/recebimento' },
      { label: 'Endereços', path: '/wms/enderecos' },
      { label: 'Picking', path: '/wms/picking' },
      { label: 'Expedição', path: '/wms/expedicao' },
    ],
    personas: ['Logística', 'Operador de armazém'],
    prerequisites: ['CDs e endereços cadastrados', 'Coletores/leitores configurados (opcional)'],
    steps: [
      { title: 'Receber mercadoria', description: 'Recebimento → escaneie NF-e de entrada → confira quantidades.' },
      { title: 'Endereçar', description: 'Put-away sugere endereço ideal com base em curva ABC e volume.' },
      { title: 'Planejar onda', description: 'Picking → gerar onda agrupa pedidos por região do armazém.' },
      { title: 'Expedir', description: 'Após packing, gere manifesto e vincule ao TMS.' },
    ],
    sections: [
      { heading: 'Coletor mobile', paragraphs: ['Rota /coletor tem UI mobile-first otimizada para operação com scanner.'] },
    ],
    faq: [{ q: 'Divergência de estoque?', a: 'Rode inventário rotativo em WMS → Inventário. Ajustes geram trilha de auditoria.' }],
    troubleshooting: [
      { problem: 'Picking sem sugestão', solution: 'Verifique se produtos têm endereço cadastrado e saldo disponível.' },
    ],
    screenshots: commonScreens(['Tela do coletor', 'Onda de picking', 'Mapa de endereços']),
  },
  {
    slug: 'compras',
    title: 'Compras',
    category: 'Operacional',
    icon: Package,
    short: 'Requisições, cotações, pedidos de compra e homologação de fornecedores.',
    overview: ['Fluxo completo: requisição → cotação múltipla → aprovação → PO → recebimento.'],
    routes: [
      { label: 'Pedidos de Compra', path: '/compras/pedidos' },
      { label: 'Cotações', path: '/compras/cotacoes' },
      { label: 'Fornecedores', path: '/compras/fornecedores' },
      { label: 'Aprovações', path: '/compras/aprovacoes' },
    ],
    personas: ['Compras', 'Gerente', 'Diretor'],
    prerequisites: ['Fornecedores cadastrados', 'Alçadas de aprovação definidas'],
    steps: [
      { title: 'Criar requisição', description: 'Comece por Requisições ou direto do MRP.' },
      { title: 'Solicitar cotação', description: 'Envie a múltiplos fornecedores; compare preços, prazo e frete.' },
      { title: 'Aprovar', description: 'Aprovadores recebem no Workflow Inbox — aprove ou rejeite com justificativa.' },
      { title: 'Emitir PO', description: 'PO enviado por e-mail ao fornecedor; recebimento vincula no WMS.' },
    ],
    sections: [],
    faq: [{ q: 'Como definir alçadas?', a: 'Administração → Workflows → configure regras por valor e centro de custo.' }],
    troubleshooting: [
      { problem: 'PO não avança', solution: 'Confira aprovações pendentes no Workflow Inbox.' },
    ],
    screenshots: commonScreens(['Cotação comparativa', 'Aprovação de PO']),
  },
  {
    slug: 'estoque',
    title: 'Estoque',
    category: 'Operacional',
    icon: Boxes,
    short: 'Produtos, Kardex, curva ABC, categorias e ajustes.',
    overview: ['Controle de saldos, movimentações, curva ABC e gestão de categorias.'],
    routes: [
      { label: 'Produtos', path: '/estoque/produtos' },
      { label: 'Kardex', path: '/estoque/kardex' },
      { label: 'Categorias', path: '/estoque/categorias' },
    ],
    personas: ['Logística', 'Compras', 'Comercial'],
    prerequisites: ['Unidades de medida e categorias definidas'],
    steps: [
      { title: 'Cadastrar produto', description: 'Informe SKU, NCM, unidade, categoria e políticas de estoque.' },
      { title: 'Consultar Kardex', description: 'Rastreie toda entrada/saída com origem (venda, compra, produção, ajuste).' },
      { title: 'Analisar curva ABC', description: 'Prioriza gestão de itens com maior giro/valor.' },
    ],
    sections: [],
    faq: [{ q: 'Não consigo excluir produto', a: 'Proteção contra exclusão: existem movimentos vinculados. Inative em vez de excluir.' }],
    troubleshooting: [{ problem: 'Saldo negativo', solution: 'Rode inventário e revise apontamentos de produção.' }],
    screenshots: commonScreens(['Ficha do produto', 'Kardex']),
  },
  {
    slug: 'tms',
    title: 'TMS — Transporte',
    category: 'Operacional',
    icon: Truck,
    short: 'Roteirização, frota, POD, live tracking e manifesto.',
    overview: ['Gestão de transportadoras, veículos, rotas otimizadas (TSP), comprovantes de entrega e rastreamento ao vivo.'],
    routes: [
      { label: 'Dashboard TMS', path: '/tms/dashboard' },
      { label: 'Rotas', path: '/tms/rotas' },
      { label: 'Frota', path: '/tms/veiculos' },
      { label: 'Live Tracking', path: '/tms/rastreamento' },
    ],
    personas: ['Logística', 'Expedição'],
    prerequisites: ['Veículos e motoristas cadastrados'],
    steps: [
      { title: 'Planejar rota', description: 'Selecione pedidos prontos, sistema otimiza (TSP) e sugere sequência.' },
      { title: 'Gerar manifesto', description: 'Vincula ao veículo e emite documento.' },
      { title: 'Capturar POD', description: 'Motorista fotografa comprovante no app; entrega é atualizada automaticamente.' },
    ],
    sections: [],
    faq: [{ q: 'Rota longa demais?', a: 'Ajuste restrições (peso, janela de entrega) e re-otimize.' }],
    troubleshooting: [{ problem: 'Live tracking sem posição', solution: 'Verifique se o app do motorista está logado e com GPS ativo.' }],
    screenshots: commonScreens(['Planejador de rotas', 'POD']),
  },
  {
    slug: 'rfid',
    title: 'RFID',
    category: 'Operacional',
    icon: Radio,
    short: 'Leitores, tags e eventos em tempo real integrados ao WMS.',
    overview: ['Rastreamento por RFID com eventos realtime que alimentam WMS e inventário.'],
    routes: [
      { label: 'Leitores', path: '/rfid/leitores' },
      { label: 'Tags', path: '/rfid/tags' },
      { label: 'Eventos', path: '/rfid/eventos' },
    ],
    personas: ['Logística', 'TI'],
    prerequisites: ['Hardware RFID configurado'],
    steps: [
      { title: 'Cadastrar leitor', description: 'Informe endereço IP e localização.' },
      { title: 'Vincular tag ao produto', description: 'Uma tag = um item rastreável.' },
      { title: 'Monitorar eventos', description: 'Feed realtime; anomalias geram alerta.' },
    ],
    sections: [],
    faq: [{ q: 'Leitor offline?', a: 'Verifique rede e status do gateway.' }],
    troubleshooting: [{ problem: 'Tag não lida', solution: 'Confirme distância e obstrução metálica.' }],
    screenshots: commonScreens(['Feed de eventos', 'Lista de leitores']),
  },
];
