import type { NavSection } from '../types';

export const financeiroSection: NavSection = {
  label: 'Financeiro',
  items: [
    {
      title: 'Financeiro',
      href: '/financeiro',
      icon: 'Wallet',
      children: [
        { title: 'Central Financeira', href: '/financeiro/central', icon: 'Zap' },
        { title: 'Dashboard', href: '/financeiro/dashboard', icon: 'BarChart3' },
        { title: 'Contas a Pagar', href: '/financeiro/pagar', icon: 'ArrowUpCircle' },
        { title: 'Contas a Receber', href: '/financeiro/receber', icon: 'ArrowDownCircle' },
        { title: 'Conta Corrente', href: '/financeiro/conta-corrente', icon: 'Users' },
        { title: 'Compensação', href: '/financeiro/compensacao', icon: 'ArrowLeftRight' },
        { title: 'Régua de Cobrança', href: '/financeiro/cobranca-automatica', icon: 'BellRing' },
        { title: 'Recorrências', href: '/financeiro/recorrencias', icon: 'RotateCw' },
        { title: 'Inadimplência', href: '/financeiro/inadimplencia', icon: 'AlertOctagon' },
        { title: 'Cenários de Caixa', href: '/financeiro/cenarios', icon: 'GitBranch' },
        { title: 'Alertas Inteligentes', href: '/financeiro/alertas', icon: 'Siren' },
        { title: 'DRE Dinâmica', href: '/financeiro/dre-dinamica', icon: 'BarChart3' },
        { title: 'Fluxo de Caixa', href: '/financeiro/fluxo', icon: 'TrendingUp' },
        { title: 'DRE (Ledger)', href: '/financeiro/dre', icon: 'LineChart' },
        { title: 'Varejo × Atacado', href: '/financeiro/segmentado', icon: 'Split' },
        { title: 'Tesouraria', href: '/financeiro/tesouraria', icon: 'Building2' },
        { title: 'Adiantamentos', href: '/financeiro/adiantamentos', icon: 'Wallet' },
        { title: 'Centros de Custo', href: '/financeiro/centros-custo', icon: 'FolderTree' },
        { title: 'Renegociações', href: '/financeiro/renegociacoes', icon: 'RefreshCw' },
        { title: 'Conciliação', href: '/financeiro/conciliacao', icon: 'CheckCircle' },
        { title: 'Conciliação por Canal', href: '/financeiro/conciliacao-canal', icon: 'Split' },
        { title: 'Cobranças PIX', href: '/financeiro/pix', icon: 'QrCode' },
        { title: 'Boletos', href: '/financeiro/boletos', icon: 'Receipt' },
        { title: 'Cheques', href: '/financeiro/cheques', icon: 'FileCheck' },
        { title: 'Inteligência IA', href: '/financeiro/inteligencia', icon: 'Brain' },
        { title: 'BI Executivo', href: '/financeiro/bi', icon: 'BarChart3' },
        { title: 'Antifraude', href: '/financeiro/antifraude', icon: 'ShieldAlert' },
        { title: 'Importar Extrato', href: '/financeiro/importar-extrato', icon: 'Upload' },
        { title: 'Auditoria Contínua', href: '/financeiro/auditoria', icon: 'ShieldCheck' },
      ],
    },
    {
      title: 'Crédito & Risco',
      href: '/credito',
      icon: 'ShieldCheck',
      children: [
        { title: 'Dashboard Risco', href: '/credito/dashboard', icon: 'BarChart3' },
        { title: 'Análise de Crédito', href: '/credito/analise', icon: 'Shield' },
        { title: 'Bloqueios', href: '/credito/bloqueios', icon: 'Lock' },
        { title: 'Cobrança', href: '/credito/cobranca', icon: 'Phone' },
      ],
    },
    {
      title: 'Contabilidade',
      href: '/contabilidade',
      icon: 'Calculator',
      children: [
        { title: 'Painel Executivo', href: '/contabilidade/painel', icon: 'BarChart3' },
        { title: 'Plano de Contas', href: '/contabilidade/plano-contas', icon: 'FolderTree' },
        { title: 'Lançamentos', href: '/contabilidade/lancamentos', icon: 'FileText' },
        { title: 'Razão Contábil', href: '/contabilidade/razao', icon: 'BookOpen' },
        { title: 'Balancete', href: '/contabilidade/balancete', icon: 'Scale' },
        { title: 'DRE', href: '/contabilidade/dre', icon: 'TrendingUp' },
        { title: 'Balanço Patrimonial', href: '/contabilidade/balanco', icon: 'Building2' },
        { title: 'Fechamento Contábil', href: '/contabilidade/fechamento', icon: 'Lock' },
      ],
    },
    {
      title: 'Fiscal',
      href: '/fiscal',
      icon: 'FileCheck',
      children: [
        { title: 'Painel Fiscal', href: '/fiscal/dashboard', icon: 'Gauge' },
        { title: 'NF-e', href: '/fiscal/nfe', icon: 'FileText' },
        { title: 'NFC-e', href: '/fiscal/nfce', icon: 'Receipt' },
        { title: 'CT-e', href: '/fiscal/cte', icon: 'FileCheck2' },
        { title: 'MDF-e', href: '/fiscal/mdfe', icon: 'ScrollText' },
        { title: 'Regras Fiscais', href: '/fiscal/regras-fiscais', icon: 'Sliders' },
        { title: 'ICMS ST', href: '/fiscal/icms-st', icon: 'Percent' },
        { title: 'DIFAL', href: '/fiscal/difal', icon: 'Globe' },
        { title: 'SPED Fiscal/Contrib.', href: '/fiscal/sped', icon: 'FileDown' },
        { title: 'EFD-Reinf', href: '/fiscal/reinf', icon: 'FileBadge' },
        { title: 'Relatórios Fiscais', href: '/fiscal/relatorios', icon: 'PieChart' },
      ],
    },
  ],
};
