import type { NavSection } from '../types';

export const logisticaSection: NavSection = {
  label: 'Logística',
  items: [
    {
      title: 'WMS',
      href: '/wms',
      icon: 'Warehouse',
      children: [
        { title: 'Dashboard WMS', href: '/wms/dashboard', icon: 'LayoutDashboard' },
        { title: 'Analytics & SLA', href: '/wms/analytics', icon: 'Gauge' },
        { title: 'Centros de Distrib.', href: '/wms/centros-distribuicao', icon: 'Building2' },
        { title: 'Armazenagem', href: '/wms/armazenagem', icon: 'Boxes' },
        { title: 'Endereços', href: '/wms/enderecos', icon: 'MapPin' },
        { title: 'Saldos', href: '/wms/saldos', icon: 'Database' },
        { title: 'Matriz Multi-Loja', href: '/wms/matriz-estoque', icon: 'LayoutGrid' },
        { title: 'Transferências entre Canais', href: '/wms/transferencias-canal', icon: 'ArrowRightLeft' },
        { title: 'Relatório Estoque × Canal', href: '/wms/relatorio-estoque-canal', icon: 'FileBarChart' },
        { title: 'Auditoria de Estoque', href: '/wms/auditoria-estoque', icon: 'ClipboardList' },
        { title: 'Reconciliação Fat. × Saída', href: '/wms/reconciliacao-faturamento', icon: 'Scale' },
        { title: 'Alocação de SKU', href: '/wms/alocacao', icon: 'Move' },
        { title: 'Lotes', href: '/wms/lotes', icon: 'Layers' },
        { title: 'Recebimento', href: '/wms/recebimento', icon: 'PackagePlus' },
        { title: 'Put-Away', href: '/wms/putaway', icon: 'ArrowDown' },
        { title: 'Ressuprimento', href: '/wms/ressuprimento', icon: 'RefreshCw' },
        { title: 'Reservas de Pedido', href: '/wms/reservas', icon: 'Bookmark' },
        { title: 'Separação (Picking)', href: '/wms/separacao', icon: 'PackageSearch' },
        { title: 'Separação de Pedidos', href: '/wms/separacao-pedidos', icon: 'ListChecks' },
        { title: 'Rota de Picking', href: '/wms/rota-picking', icon: 'Route' },
        { title: 'Ondas', href: '/wms/ondas', icon: 'Layers' },
        { title: 'Wave Planning v2', href: '/wms/wave-planning', icon: 'Waves' },
        { title: 'Embalagem (Packing)', href: '/wms/embalagem', icon: 'PackageCheck' },
        { title: 'Conferência', href: '/wms/conferencia', icon: 'ScanBarcode' },
        { title: 'Cross-Docking', href: '/wms/cross-docking', icon: 'Shuffle' },
        { title: 'Montagem de Kits', href: '/wms/kits', icon: 'Boxes' },
        { title: 'Docas', href: '/wms/docas', icon: 'DoorOpen' },
        { title: 'Agenda de Docas', href: '/wms/agenda-docas', icon: 'CalendarClock' },
        { title: 'Pátio (Yard)', href: '/wms/yard', icon: 'ParkingSquare' },
        { title: 'Expedição', href: '/wms/expedicao', icon: 'Truck' },
        { title: 'Scorecard Transp.', href: '/wms/scorecard-transportadoras', icon: 'Trophy' },
        { title: 'Devoluções', href: '/wms/devolucoes', icon: 'RotateCcw' },
        { title: 'Qualidade & Quarentena', href: '/wms/qualidade', icon: 'ShieldCheck' },
        { title: 'Inventário', href: '/wms/inventario', icon: 'ClipboardList' },
        { title: 'Inventário Cíclico', href: '/wms/inventario-ciclico', icon: 'ClipboardCheck' },
        { title: 'Movimentações', href: '/wms/movimentacoes', icon: 'MoveHorizontal' },
        { title: 'Mão de Obra', href: '/wms/mao-de-obra', icon: 'Users' },
        { title: 'Slotting', href: '/wms/slotting', icon: 'Grid3x3' },
        { title: 'Digital Twin 3D', href: '/wms/twin', icon: 'Box' },
        { title: 'Inteligência ML', href: '/wms/inteligencia', icon: 'Sparkles' },
        { title: 'Faturamento 3PL', href: '/wms/faturamento-3pl', icon: 'DollarSign' },
        { title: 'IA WMS', href: '/wms/ia', icon: 'Brain' },
      ],
    },
    {
      title: 'RFID',
      href: '/rfid',
      icon: 'Radio',
      children: [
        { title: 'Dashboard RFID', href: '/rfid/dashboard', icon: 'LayoutDashboard' },
        { title: 'Leitores', href: '/rfid/leitores', icon: 'Wifi' },
        { title: 'Tags', href: '/rfid/tags', icon: 'Tag' },
        { title: 'Eventos', href: '/rfid/eventos', icon: 'Activity' },
        { title: 'Integração WMS', href: '/rfid/integracao', icon: 'ArrowLeftRight' },
      ],
    },
    {
      title: 'TMS - Transporte',
      href: '/tms',
      icon: 'Truck',
      children: [
        { title: 'Dashboard TMS', href: '/tms/dashboard', icon: 'LayoutDashboard' },
        { title: 'Transportadoras', href: '/tms/transportadoras', icon: 'Building2' },
        { title: 'Veículos / Frota', href: '/tms/veiculos', icon: 'Truck' },
        { title: 'Rotas de Entrega', href: '/tms/rotas', icon: 'MapPin' },
        { title: 'Rastreamento ao Vivo', href: '/tms/live', icon: 'Navigation' },
        { title: 'Comprovantes', href: '/tms/comprovantes', icon: 'FileCheck' },
      ],
    },
  ],
};
