import type { NavSection } from '../types';

export const operacionalSection: NavSection = {
  label: 'Operacional',
  items: [
    {
      title: 'Fluxo Operacional',
      href: '/operacional',
      icon: 'ArrowRightLeft',
      children: [
        { title: 'Dashboard Operacional', href: '/operacional/dashboard', icon: 'BarChart3' },
        { title: 'Acompanhamento', href: '/operacional/rastreamento', icon: 'Eye' },
        { title: 'Separação', href: '/operacional/separacao', icon: 'PackageSearch' },
        { title: 'Conferência', href: '/operacional/conferencia', icon: 'ClipboardCheck' },
        { title: 'Faturamento', href: '/operacional/faturamento', icon: 'FileText' },
        { title: 'Expedição', href: '/operacional/expedicao', icon: 'Truck' },
      ],
    },
    {
      title: 'Comercial',
      href: '/comercial',
      icon: 'Users',
      children: [
        { title: 'CRM Enterprise', href: '/comercial/crm', icon: 'Target' },
        { title: 'Dashboard', href: '/comercial/dashboard', icon: 'BarChart3' },
        { title: '🛒 Painel Único (PDV)', href: '/comercial/pdv', icon: 'ShoppingCart' },
        { title: '⚡ O Que Fazer Hoje', href: '/comercial/execucao', icon: 'Zap' },
        { title: 'Painel Vendedor', href: '/comercial/vendedor', icon: 'Zap' },
        { title: 'Funil Comercial', href: '/comercial/funil', icon: 'Filter' },
        { title: 'Clientes', href: '/comercial/clientes', icon: 'UserCircle' },
        { title: 'Perfil Comercial', href: '/comercial/perfil-clientes', icon: 'Crown' },
        { title: 'Representantes', href: '/comercial/representantes', icon: 'UserCheck' },
        { title: 'Pedidos', href: '/comercial/pedidos', icon: 'ClipboardList' },
        { title: 'Orçamentos', href: '/comercial/orcamentos', icon: 'FileText' },
        { title: 'Comissões', href: '/comercial/comissoes', icon: 'DollarSign' },
        { title: 'Metas', href: '/comercial/metas', icon: 'Target' },
        { title: 'Forecast', href: '/comercial/forecast', icon: 'TrendingUp' },
        { title: 'Campanhas', href: '/comercial/campanhas', icon: 'Megaphone' },
        { title: 'Performance', href: '/comercial/performance', icon: 'BarChart3' },
        { title: 'Relatório Vendas × Canal', href: '/comercial/relatorio-canal', icon: 'FileBarChart' },
        { title: '📘 Playbook', href: '/comercial/playbook', icon: 'BookOpen' },
        { title: '🎮 Gamificação', href: '/comercial/gamificacao', icon: 'Trophy' },
        { title: '🧠 IA Comercial', href: '/comercial/ia', icon: 'Brain' },
        { title: '🤖 Automação', href: '/comercial/automacao', icon: 'Bot' },
      ],
    },
    {
      title: 'Relacionamento',
      href: '/relacionamento',
      icon: 'Heart',
      children: [
        { title: 'NPS · Dashboard', href: '/relacionamento/nps/dashboard', icon: 'BarChart3' },
        { title: 'Campanhas', href: '/relacionamento/nps/campanhas', icon: 'Megaphone' },
        { title: 'Pesquisas', href: '/relacionamento/nps/pesquisas', icon: 'ClipboardList' },
        { title: 'Convites', href: '/relacionamento/nps/convites', icon: 'Send' },
        { title: 'Respostas', href: '/relacionamento/nps/respostas', icon: 'MessageSquare' },
        { title: 'Relatórios', href: '/relacionamento/nps/relatorios', icon: 'FileText' },
        { title: 'Templates', href: '/relacionamento/nps/templates', icon: 'Palette' },
        { title: 'Automações', href: '/relacionamento/nps/automacoes', icon: 'Zap' },
        { title: 'Configurações', href: '/relacionamento/nps/configuracoes', icon: 'Settings' },
      ],
    },
    {
      title: 'Compras',
      href: '/compras',
      icon: 'ShoppingCart',
      children: [
        { title: 'Fornecedores', href: '/compras/fornecedores', icon: 'Building2' },
        { title: 'Pedidos de Compra', href: '/compras/pedidos', icon: 'ClipboardList' },
        { title: 'Cotações', href: '/compras/cotacoes', icon: 'FileSearch' },
      ],
    },
    {
      title: 'Produção',
      href: '/producao',
      icon: 'Factory',
      children: [
        { title: 'Dashboard Industrial', href: '/producao/dashboard-industrial', icon: 'Gauge' },
        { title: 'Painel PCP', href: '/producao/pcp', icon: 'BarChart3' },
        { title: 'Ordens de Produção', href: '/producao/ordens', icon: 'ClipboardCheck' },
        { title: '📋 Kanban', href: '/producao/kanban', icon: 'Columns' },
        { title: '🏭 Terceirização', href: '/producao/terceirizacao', icon: 'Truck' },
        { title: 'Fila de Produção', href: '/producao/fila', icon: 'ListOrdered' },
        { title: 'Agendamento', href: '/producao/programacao', icon: 'CalendarClock' },
        { title: 'Chão de Fábrica', href: '/producao/chao-de-fabrica', icon: 'Activity' },
        { title: '📲 Terminal Operador', href: '/producao/terminal', icon: 'Smartphone' },
        { title: 'Apontamentos', href: '/producao/apontamento', icon: 'Timer' },
        { title: 'Setores', href: '/producao/setores', icon: 'Building2' },
        { title: '📏 Linhas Produtivas', href: '/producao/linhas', icon: 'Rows3' },
        { title: '🔧 Recursos', href: '/producao/recursos', icon: 'Wrench' },
        { title: '🗺️ Rotas Produtivas', href: '/producao/roteiros', icon: 'Route' },
        { title: 'Etapas Produtivas', href: '/producao/etapas', icon: 'Layers' },
        { title: '📄 Fichas Técnicas', href: '/producao/fichas', icon: 'FileText' },
        { title: '⚡ Capacidade', href: '/producao/capacidade', icon: 'Zap' },
        { title: 'Controle de Qualidade', href: '/producao/qualidade', icon: 'ShieldCheck' },
        { title: '🔍 Rastreabilidade', href: '/producao/rastreabilidade', icon: 'Search' },
        { title: '📦 MRP', href: '/producao/mrp', icon: 'Package' },
        { title: 'Estoque de Insumos', href: '/producao/insumos', icon: 'Boxes' },
        { title: 'Consumo MP', href: '/producao/consumo', icon: 'PackageMinus' },
        { title: 'Custo e Lucro', href: '/producao/custos', icon: 'Calculator' },
        { title: '📊 BI Industrial', href: '/producao/bi', icon: 'PieChart' },
        { title: '📊 OEE', href: '/producao/oee', icon: 'CircleGauge' },
        { title: '🧠 IA Produção', href: '/producao/ia', icon: 'Brain' },
        { title: '🤖 ML Predições', href: '/producao/previsoes', icon: 'Sparkles' },
        { title: '🔮 Digital Twin', href: '/producao/twin', icon: 'Cpu' },
        { title: '🚀 APS', href: '/producao/aps', icon: 'Rocket' },
        { title: '🌐 IoT Monitor', href: '/producao/iot', icon: 'Wifi' },
      ],
    },
    {
      title: 'Estoque',
      href: '/estoque',
      icon: 'Package',
      children: [
        { title: 'Produtos', href: '/estoque/produtos', icon: 'Box' },
        { title: 'Categorias', href: '/estoque/categorias', icon: 'FolderTree' },
        { title: 'Movimentações', href: '/estoque/movimentacoes', icon: 'ArrowLeftRight' },
        { title: 'Kardex', href: '/estoque/kardex', icon: 'BookOpen' },
        { title: 'Saldos', href: '/estoque/saldos', icon: 'Calculator' },
      ],
    },
  ],
};
